# compat shim — GENERATED by consolidation Stage 1 phase B; do not edit by hand.
# Aliases agentic_dynamics.<plane>.<mod> so `instrument.<mod>` IS the real module:
# import, attribute access, and mock-patching are all transparent. Removed in phase E.
import sys as _sys
import agentic_dynamics.core.paths as _impl

_sys.modules[__name__] = _impl
