"""WebSocket-based notification server.

The server accepts WebSocket connections, assigns each client a unique ID,
supports broadcasting messages to all connected clients, sending direct
messages to a single client, and routing messages to channel subscribers.
It also exposes a ``GET /health`` REST endpoint that reports the number of
connected clients, plus channel introspection endpoints.

Wire protocol
-------------
Every frame sent over the wire is base64-encoded. The payload of a frame is
the JSON serialization of a message with the following shape::

    {
        "type": "broadcast" | "direct" | "system" | "subscribe" | "unsubscribe",
        "payload": {...},
        "timestamp": "<ISO-8601 UTC string>",
    }

* ``system`` messages are generated by the server (e.g. connection handshake).
* ``broadcast`` messages sent by a client are relayed to every connected client,
  unless they carry a ``channel`` field, in which case they are relayed only to
  clients subscribed to that channel.
* ``direct`` messages carry a ``payload["to"]`` target client ID and are
  relayed only to that client.
* ``subscribe`` / ``unsubscribe`` messages carry a channel name (in ``payload``
  or as a top-level ``channel`` field) and add/remove the sender from that
  channel's subscriber list.

Channels
--------
* Clients can subscribe to any number of named channels and can
  subscribe/unsubscribe dynamically.
* A ``channel`` field (top-level or inside ``payload``) on a message restricts
  delivery to the subscribers of that channel.
"""

from __future__ import annotations

import asyncio
import base64
import json
import threading
import uuid
from datetime import datetime, timezone
from typing import Any, Awaitable, Callable, Optional
from urllib.parse import unquote

from websockets.asyncio.server import ServerConnection, serve
from websockets.exceptions import ConnectionClosed

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8765

SUPPORTED_TYPES = ("broadcast", "direct", "system", "subscribe", "unsubscribe")


def utc_now() -> str:
    """Return the current UTC timestamp as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def encode_frame(message: dict) -> str:
    """Serialize a message dict to the base64-encoded wire format."""
    return base64.b64encode(
        json.dumps(message, separators=(",", ":")).encode("utf-8")
    ).decode("ascii")


def decode_frame(frame: str | bytes) -> dict:
    """Decode a base64-encoded wire frame back into a message dict."""
    if isinstance(frame, bytes):
        frame = frame.decode("utf-8")
    payload = base64.b64decode(frame)
    return json.loads(payload.decode("utf-8"))


def get_channel(message: dict) -> Optional[str]:
    """Extract a channel name from a message (top-level or inside payload)."""
    channel = message.get("channel")
    if channel is None and isinstance(message.get("payload"), dict):
        channel = message.get("payload").get("channel")
    return channel


class ClientRegistry:
    """Thread-safe registry mapping client IDs to their WebSocket connections."""

    def __init__(self) -> None:
        self._clients: dict[str, ServerConnection] = {}
        self._lock = threading.Lock()

    def add(self, client_id: str, websocket: ServerConnection) -> None:
        with self._lock:
            self._clients[client_id] = websocket

    def remove(self, client_id: str) -> Optional[ServerConnection]:
        with self._lock:
            return self._clients.pop(client_id, None)

    def get(self, client_id: str) -> Optional[ServerConnection]:
        with self._lock:
            return self._clients.get(client_id)

    def snapshot(self) -> list[tuple[str, ServerConnection]]:
        with self._lock:
            return list(self._clients.items())

    def count(self) -> int:
        with self._lock:
            return len(self._clients)

    def __contains__(self, client_id: str) -> bool:
        with self._lock:
            return client_id in self._clients


class ChannelRegistry:
    """Thread-safe registry mapping channel names to subscriber client IDs."""

    def __init__(self) -> None:
        self._channels: dict[str, set[str]] = {}
        self._lock = threading.Lock()

    def subscribe(self, client_id: str, channel: str) -> None:
        with self._lock:
            self._channels.setdefault(channel, set()).add(client_id)

    def unsubscribe(self, client_id: str, channel: str) -> None:
        with self._lock:
            subscribers = self._channels.get(channel)
            if subscribers is None:
                return
            subscribers.discard(client_id)
            if not subscribers:
                del self._channels[channel]

    def remove_client(self, client_id: str) -> None:
        with self._lock:
            for channel in list(self._channels):
                subscribers = self._channels[channel]
                subscribers.discard(client_id)
                if not subscribers:
                    del self._channels[channel]

    def subscribers(self, channel: str) -> list[str]:
        with self._lock:
            return list(self._channels.get(channel, set()))

    def counts(self) -> dict[str, int]:
        with self._lock:
            return {name: len(subs) for name, subs in self._channels.items()}


class NotificationServer:
    """Async notification server managing thread-safe registries."""

    def __init__(self) -> None:
        self.registry = ClientRegistry()
        self.channels = ChannelRegistry()

    # ── Outbound helpers ───────────────────────────────────────

    async def send_to(self, client_id: str, message: dict) -> bool:
        """Send a message to a single client. Returns True on success."""
        websocket = self.registry.get(client_id)
        if websocket is None:
            return False
        try:
            await websocket.send(encode_frame(message))
        except Exception:
            self.registry.remove(client_id)
            self.channels.remove_client(client_id)
            return False
        return True

    async def broadcast(self, message: dict) -> int:
        """Send a message to every connected client.

        Returns the number of clients the message was delivered to.
        """
        clients = self.registry.snapshot()
        results = await asyncio.gather(
            *(self.send_to(client_id, message) for client_id, _ in clients),
            return_exceptions=True,
        )
        return sum(1 for ok in results if ok is True)

    async def publish(self, channel: str, message: dict) -> int:
        """Send a message to every subscriber of a channel.

        Returns the number of clients the message was delivered to.
        """
        subscribers = self.channels.subscribers(channel)
        results = await asyncio.gather(
            *(self.send_to(client_id, message) for client_id in subscribers),
            return_exceptions=True,
        )
        return sum(1 for ok in results if ok is True)

    # ── Inbound handling ───────────────────────────────────────

    async def _handle_message(self, sender_id: str, message: dict) -> None:
        msg_type = message.get("type")
        payload = message.get("payload") if isinstance(message.get("payload"), dict) else {}

        if msg_type == "broadcast":
            outgoing = {
                "type": "broadcast",
                "payload": payload,
                "timestamp": utc_now(),
            }
            channel = get_channel(message)
            if isinstance(channel, str) and channel:
                outgoing["channel"] = channel
                await self.publish(channel, outgoing)
            else:
                await self.broadcast(outgoing)

        elif msg_type == "subscribe":
            channel = get_channel(message)
            if not isinstance(channel, str) or not channel:
                await self.send_to(
                    sender_id,
                    {
                        "type": "system",
                        "payload": {"error": "subscribe requires a channel name"},
                        "timestamp": utc_now(),
                    },
                )
                return
            self.channels.subscribe(sender_id, channel)

        elif msg_type == "unsubscribe":
            channel = get_channel(message)
            if not isinstance(channel, str) or not channel:
                await self.send_to(
                    sender_id,
                    {
                        "type": "system",
                        "payload": {"error": "unsubscribe requires a channel name"},
                        "timestamp": utc_now(),
                    },
                )
                return
            self.channels.unsubscribe(sender_id, channel)

        elif msg_type == "direct":
            target = payload.get("to")
            if target is None or not isinstance(target, str):
                await self.send_to(
                    sender_id,
                    {
                        "type": "system",
                        "payload": {"error": "direct message requires payload['to']"},
                        "timestamp": utc_now(),
                    },
                )
                return
            outgoing = {
                "type": "direct",
                "payload": {"from": sender_id, "message": payload.get("message")},
                "timestamp": utc_now(),
            }
            delivered = await self.send_to(target, outgoing)
            if not delivered:
                await self.send_to(
                    sender_id,
                    {
                        "type": "system",
                        "payload": {"error": f"target client {target!r} not connected"},
                        "timestamp": utc_now(),
                    },
                )

        else:
            await self.send_to(
                sender_id,
                {
                    "type": "system",
                    "payload": {
                        "error": f"unsupported message type {msg_type!r}; "
                        f"expected one of {SUPPORTED_TYPES}",
                    },
                    "timestamp": utc_now(),
                },
            )

    async def handler(self, websocket: ServerConnection) -> None:
        """Handle a single WebSocket connection lifecycle."""
        client_id = str(uuid.uuid4())
        self.registry.add(client_id, websocket)
        try:
            await websocket.send(
                encode_frame(
                    {
                        "type": "system",
                        "payload": {"event": "connected", "client_id": client_id},
                        "timestamp": utc_now(),
                    }
                )
            )
            while True:
                try:
                    frame = await websocket.recv()
                except ConnectionClosed:
                    break

                try:
                    message = decode_frame(frame)
                except Exception:
                    await self.send_to(
                        client_id,
                        {
                            "type": "system",
                            "payload": {"error": "invalid message: expected base64-encoded JSON"},
                            "timestamp": utc_now(),
                        },
                    )
                    continue

                if not isinstance(message, dict):
                    await self.send_to(
                        client_id,
                        {
                            "type": "system",
                            "payload": {"error": "invalid message: expected a JSON object"},
                            "timestamp": utc_now(),
                        },
                    )
                    continue

                await self._handle_message(client_id, message)
        finally:
            self.registry.remove(client_id)
            self.channels.remove_client(client_id)

    # ── REST endpoints ─────────────────────────────────────────

    def _json_response(self, connection: ServerConnection, status: int, data: Any) -> Any:
        body = json.dumps(data)
        response = connection.respond(status, body)
        response.headers.pop("Content-Type")
        response.headers["Content-Type"] = "application/json; charset=utf-8"
        return response

    async def process_request(
        self, connection: ServerConnection, request: Any
    ) -> Any:
        """Serve REST endpoints over plain HTTP, otherwise allow the WS handshake."""
        path = request.path

        if path == "/health":
            return self._json_response(
                connection, 200, {"connected_clients": self.registry.count()}
            )

        if path == "/channels":
            return self._json_response(connection, 200, self.channels.counts())

        if path.startswith("/channels/") and path.endswith("/subscribers"):
            name = unquote(path[len("/channels/"):-len("/subscribers")])
            return self._json_response(
                connection, 200, self.channels.subscribers(name)
            )

        return None


def create_server(
    app: NotificationServer,
    host: str = DEFAULT_HOST,
    port: int = DEFAULT_PORT,
) -> Callable[[], Awaitable[Any]]:
    """Return an async server factory bound to ``app``."""
    return serve(
        app.handler,
        host,
        port,
        process_request=app.process_request,
    )


async def main(host: str = DEFAULT_HOST, port: int = DEFAULT_PORT) -> None:
    app = NotificationServer()
    async with serve(app.handler, host, port, process_request=app.process_request):
        await asyncio.Future()  # run forever


if __name__ == "__main__":
    asyncio.run(main())
