"""Notification server with a pluggable transport layer.

The server routes notification messages (broadcast, direct, channel, system)
between connected clients, persists relayed messages, and optionally uses a
Redis pub/sub backbone for cross-instance delivery.

Transport layer
---------------
The wire-level mechanics of accepting client connections and delivering
messages to them are abstracted behind the :class:`BaseTransport` interface.
The core :class:`NotificationServer` logic (message routing, channel
subscriptions, persistence, Redis backbone) is transport-agnostic and only
communicates with clients through the transport. Concrete transports provide
the actual connection handling:

* :class:`WebSocketTransport` — the default, backed by the ``websockets``
  library. It accepts WebSocket connections and serves the REST endpoints
  (``/health``, ``/channels``, ``/messages``) on the same port.

Additional transports (SSE, polling, raw TCP, ...) can be added by subclassing
:class:`BaseTransport` and registering them in ``TRANSPORT_REGISTRY``. The
active transport is selected with the ``TRANSPORT`` env var (defaulting to
``websocket``) or by passing a ``transport`` argument to
:class:`NotificationServer`.

Wire protocol
-------------
Every frame sent over the wire is base64-encoded. The payload of a frame is
the JSON serialization of a message with the following shape::

    {
        "type": "broadcast" | "direct" | "system" | "subscribe" | "unsubscribe",
        "payload": {...},
        "timestamp": "<ISO-8601 UTC string>",
    }

* ``system`` messages are generated by the server (e.g. connection handshake).
* ``broadcast`` messages sent by a client are relayed to every connected client,
  unless they carry a ``channel`` field, in which case they are relayed only to
  clients subscribed to that channel.
* ``direct`` messages carry a ``payload["to"]`` target client ID and are
  relayed only to that client.
* ``subscribe`` / ``unsubscribe`` messages carry a channel name (in ``payload``
  or as a top-level ``channel`` field) and add/remove the sender from that
  channel's subscriber list.

Channels
--------
* Clients can subscribe to any number of named channels and can
  subscribe/unsubscribe dynamically.
* A ``channel`` field (top-level or inside ``payload``) on a message restricts
  delivery to the subscribers of that channel.

Redis backbone
--------------
When a Redis broker is configured (``REDIS_URL`` env var or ``redis_client``),
the server publishes messages to Redis pub/sub channels and a background worker
subscribes to Redis and delivers messages to locally connected clients. This
lets multiple server instances share one Redis backbone. Client connection
state (connected clients and their channel subscriptions) is mirrored into
Redis so it survives a server restart.

Persistence
-----------
All relayed messages are stored in a SQLite database (``DATABASE_URL`` env var,
defaulting to ``messages.db``) and are exposed via ``GET /messages``.
"""

from __future__ import annotations

import asyncio
import base64
import json
import os
import sqlite3
import threading
import time
import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timezone, timedelta
from typing import Any, Awaitable, Callable, Optional
from urllib.parse import unquote, urlsplit, parse_qsl

from websockets.asyncio.server import ServerConnection, serve
from websockets.exceptions import ConnectionClosed

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8765

SUPPORTED_TYPES = ("broadcast", "direct", "system", "subscribe", "unsubscribe")

# ── Configuration ─────────────────────────────────────────────
REDIS_URL = os.environ.get("REDIS_URL")
DATABASE_URL = os.environ.get("DATABASE_URL", "messages.db")

DEFAULT_RATE_LIMIT = 100
DEFAULT_MESSAGE_TTL_DAYS = 7
CLEANUP_INTERVAL_SECONDS = 3600


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return default
    try:
        return int(raw)
    except ValueError:
        return default


#: Per-client message rate limit (messages per minute), read from ``RATE_LIMIT``.
RATE_LIMIT = _env_int("RATE_LIMIT", DEFAULT_RATE_LIMIT)

#: Age (in days) after which persisted messages are cleaned up, from
#: ``MESSAGE_TTL_DAYS``.
MESSAGE_TTL_DAYS = _env_int("MESSAGE_TTL_DAYS", DEFAULT_MESSAGE_TTL_DAYS)

# Name of the env var used to select the active transport, and the fallback
# transport name when it is unset. The value is read dynamically at server
# construction time so it can be changed before creating a server.
TRANSPORT_ENV = "TRANSPORT"
DEFAULT_TRANSPORT = "websocket"

#: Current value of the ``TRANSPORT`` env var (snapshot at import time).
TRANSPORT = os.environ.get(TRANSPORT_ENV, DEFAULT_TRANSPORT)

# Prefix for all Redis keys/channels used by the backbone.
REDIS_PREFIX = "notifications:"
REDIS_SUBSCRIBE_PATTERN = REDIS_PREFIX + "*"

DEFAULT_LIMIT = 50


def utc_now() -> str:
    """Return the current UTC timestamp as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def _parse_timestamp(value: str) -> Optional[datetime]:
    """Parse an ISO-8601 timestamp, treating naive values as UTC."""
    if value is None:
        return None
    try:
        dt = datetime.fromisoformat(str(value))
    except (TypeError, ValueError):
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def encode_frame(message: dict) -> str:
    """Serialize a message dict to the base64-encoded wire format."""
    return base64.b64encode(
        json.dumps(message, separators=(",", ":")).encode("utf-8")
    ).decode("ascii")


def decode_frame(frame: str | bytes) -> dict:
    """Decode a base64-encoded wire frame back into a message dict."""
    if isinstance(frame, bytes):
        frame = frame.decode("utf-8")
    payload = base64.b64decode(frame)
    return json.loads(payload.decode("utf-8"))


def get_channel(message: dict) -> Optional[str]:
    """Extract a channel name from a message (top-level or inside payload)."""
    channel = message.get("channel")
    if channel is None and isinstance(message.get("payload"), dict):
        channel = message.get("payload").get("channel")
    return channel


class MessageStore:
    """SQLite-backed message history.

    Every message relayed by the server is persisted to a ``messages`` table
    with columns ``id``, ``channel``, ``type``, ``payload`` and ``timestamp``.
    The ``payload`` column stores a JSON-serialized object.
    """

    def __init__(self, database_path: str) -> None:
        self.database_path = database_path
        self._lock = threading.Lock()
        self._init_db()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.database_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        conn = self._connect()
        try:
            conn.execute(
                "CREATE TABLE IF NOT EXISTS messages ("
                "  id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "  channel TEXT,"
                "  type TEXT,"
                "  payload TEXT,"
                "  timestamp TEXT"
                ")"
            )
            conn.commit()
        finally:
            conn.close()

    def save(self, channel: str, type_: str, payload: dict, timestamp: str) -> None:
        conn = self._connect()
        try:
            with self._lock:
                conn.execute(
                    "INSERT INTO messages (channel, type, payload, timestamp)"
                    " VALUES (?, ?, ?, ?)",
                    (channel, type_, json.dumps(payload), timestamp),
                )
                conn.commit()
        finally:
            conn.close()

    def list(self, limit: int = DEFAULT_LIMIT, offset: int = 0) -> list[dict]:
        conn = self._connect()
        try:
            rows = conn.execute(
                "SELECT id, channel, type, payload, timestamp FROM messages"
                " ORDER BY id DESC LIMIT ? OFFSET ?",
                (limit, offset),
            ).fetchall()
        finally:
            conn.close()
        result = []
        for row in rows:
            item = dict(row)
            try:
                item["payload"] = json.loads(item["payload"])
            except (TypeError, ValueError):
                item["payload"] = {}
            result.append(item)
        return result

    def history(
        self,
        channel: Optional[str] = None,
        since: Optional[str] = None,
        limit: int = DEFAULT_LIMIT,
    ) -> tuple[list[dict], bool]:
        """Return messages for a channel/time range in chronological order.

        ``since`` is an inclusive ISO-8601 timestamp lower bound. Returns a
        ``(messages, has_more)`` tuple where ``has_more`` is ``True`` when more
        than ``limit`` matching messages exist (so callers can paginate).
        """
        try:
            limit = int(limit)
        except (TypeError, ValueError):
            limit = DEFAULT_LIMIT
        limit = max(1, limit)

        query = "SELECT id, channel, type, payload, timestamp FROM messages"
        clauses: list[str] = []
        params: list[Any] = []
        if channel is not None:
            clauses.append("channel = ?")
            params.append(channel)
        if since is not None:
            clauses.append("timestamp >= ?")
            params.append(since)
        if clauses:
            query += " WHERE " + " AND ".join(clauses)
        query += " ORDER BY timestamp ASC, id ASC LIMIT ?"
        params.append(limit + 1)

        conn = self._connect()
        try:
            rows = conn.execute(query, params).fetchall()
        finally:
            conn.close()

        has_more = len(rows) > limit
        rows = rows[:limit]
        result = []
        for row in rows:
            item = dict(row)
            try:
                item["payload"] = json.loads(item["payload"])
            except (TypeError, ValueError):
                item["payload"] = {}
            result.append(item)
        return result, has_more

    def delete_older_than(self, cutoff: str) -> int:
        """Delete messages whose timestamp is strictly before ``cutoff``.

        Returns the number of deleted rows.
        """
        cutoff_dt = _parse_timestamp(cutoff)
        if cutoff_dt is None:
            return 0
        conn = self._connect()
        try:
            with self._lock:
                rows = conn.execute("SELECT id, timestamp FROM messages").fetchall()
                stale_ids = []
                for row in rows:
                    ts_dt = _parse_timestamp(row["timestamp"])
                    if ts_dt is not None and ts_dt < cutoff_dt:
                        stale_ids.append(row["id"])
                if stale_ids:
                    conn.executemany(
                        "DELETE FROM messages WHERE id = ?",
                        [(i,) for i in stale_ids],
                    )
                    conn.commit()
                return len(stale_ids)
        finally:
            conn.close()


class ClientRegistry:
    """Thread-safe registry mapping client IDs to their transport connections."""

    def __init__(self) -> None:
        self._clients: dict[str, Any] = {}
        self._lock = threading.Lock()

    def add(self, client_id: str, connection: Any) -> None:
        with self._lock:
            self._clients[client_id] = connection

    def remove(self, client_id: str) -> Optional[Any]:
        with self._lock:
            return self._clients.pop(client_id, None)

    def get(self, client_id: str) -> Optional[Any]:
        with self._lock:
            return self._clients.get(client_id)

    def snapshot(self) -> list[tuple[str, Any]]:
        with self._lock:
            return list(self._clients.items())

    def count(self) -> int:
        with self._lock:
            return len(self._clients)

    def __contains__(self, client_id: str) -> bool:
        with self._lock:
            return client_id in self._clients


class ChannelRegistry:
    """Thread-safe registry mapping channel names to subscriber client IDs."""

    def __init__(self) -> None:
        self._channels: dict[str, set[str]] = {}
        self._lock = threading.Lock()

    def subscribe(self, client_id: str, channel: str) -> None:
        with self._lock:
            self._channels.setdefault(channel, set()).add(client_id)

    def unsubscribe(self, client_id: str, channel: str) -> None:
        with self._lock:
            subscribers = self._channels.get(channel)
            if subscribers is None:
                return
            subscribers.discard(client_id)
            if not subscribers:
                del self._channels[channel]

    def remove_client(self, client_id: str) -> None:
        with self._lock:
            for channel in list(self._channels):
                subscribers = self._channels[channel]
                subscribers.discard(client_id)
                if not subscribers:
                    del self._channels[channel]

    def subscribers(self, channel: str) -> list[str]:
        with self._lock:
            return list(self._channels.get(channel, set()))

    def counts(self) -> dict[str, int]:
        with self._lock:
            return {name: len(subs) for name, subs in self._channels.items()}


class BaseTransport(ABC):
    """Abstract interface for transport mechanisms.

    A transport encapsulates the wire-level mechanics of accepting client
    connections and delivering messages to them. The core
    :class:`NotificationServer` is transport-agnostic: it talks to clients
    exclusively through this interface, so new transports (SSE, polling, raw
    TCP, ...) can be added without touching the core notification logic.

    Transports hold a reference back to the :class:`NotificationServer`
    (``self.server``) so they can look up connection state and hand inbound
    messages to the core logic.
    """

    def __init__(self, server: Optional["NotificationServer"] = None) -> None:
        self.server = server

    @abstractmethod
    async def on_connect(self, client_id: str, connection: Any) -> None:
        """Register a newly connected client.

        ``connection`` is the transport-specific handle (e.g. a WebSocket
        connection) that will be used to deliver messages to ``client_id``.
        """

    @abstractmethod
    async def on_disconnect(self, client_id: str) -> None:
        """Deregister a client that has disconnected."""

    @abstractmethod
    async def send_message(self, client_id: str, message: dict) -> bool:
        """Deliver ``message`` to a single client.

        Return ``True`` on success and ``False`` if the client is unknown or
        the delivery failed.
        """

    @abstractmethod
    async def broadcast(self, message: dict) -> int:
        """Deliver ``message`` to every connected client.

        Return the number of clients the message was delivered to.
        """

    def create_server(
        self, host: str = DEFAULT_HOST, port: int = DEFAULT_PORT
    ) -> Callable[[], Awaitable[Any]]:
        """Return an async server factory for this transport."""
        raise NotImplementedError


class WebSocketTransport(BaseTransport):
    """WebSocket transport backed by the ``websockets`` library.

    Encapsulates all WebSocket-specific wire logic: accepting connections,
    reading/writing base64-encoded JSON frames, and exposing the HTTP REST
    endpoints on the same port via ``process_request``.
    """

    async def on_connect(self, client_id: str, connection: Any) -> None:
        self.server.registry.add(client_id, connection)

    async def on_disconnect(self, client_id: str) -> None:
        self.server.registry.remove(client_id)
        self.server.channels.remove_client(client_id)

    async def send_message(self, client_id: str, message: dict) -> bool:
        websocket = self.server.registry.get(client_id)
        if websocket is None:
            return False
        try:
            await websocket.send(encode_frame(message))
        except Exception:
            await self.on_disconnect(client_id)
            return False
        return True

    async def broadcast(self, message: dict) -> int:
        clients = self.server.registry.snapshot()
        results = await asyncio.gather(
            *(self.send_message(client_id, message) for client_id, _ in clients),
            return_exceptions=True,
        )
        return sum(1 for ok in results if ok is True)

    async def handler(self, websocket: ServerConnection) -> None:
        """Handle a single WebSocket connection lifecycle."""
        client_id = str(uuid.uuid4())
        await self.on_connect(client_id, websocket)
        await self.server._register_client(client_id)
        try:
            await websocket.send(
                encode_frame(
                    {
                        "type": "system",
                        "payload": {"event": "connected", "client_id": client_id},
                        "timestamp": utc_now(),
                    }
                )
            )
            while True:
                try:
                    frame = await websocket.recv()
                except ConnectionClosed:
                    break

                try:
                    message = decode_frame(frame)
                except Exception:
                    await self.send_message(
                        client_id,
                        {
                            "type": "system",
                            "payload": {"error": "invalid message: expected base64-encoded JSON"},
                            "timestamp": utc_now(),
                        },
                    )
                    continue

                if not isinstance(message, dict):
                    await self.send_message(
                        client_id,
                        {
                            "type": "system",
                            "payload": {"error": "invalid message: expected a JSON object"},
                            "timestamp": utc_now(),
                        },
                    )
                    continue

                await self.server._handle_message(client_id, message)
        finally:
            await self.on_disconnect(client_id)
            await self.server._unregister_client(client_id)

    def create_server(
        self, host: str = DEFAULT_HOST, port: int = DEFAULT_PORT
    ) -> Callable[[], Awaitable[Any]]:
        """Return an async ``serve`` factory bound to this transport's handler."""
        return serve(
            self.handler,
            host,
            port,
            process_request=self.server.process_request,
        )


# Registry of available transports, keyed by name. Additional transports can
# be registered here without modifying the core notification logic.
TRANSPORT_REGISTRY: dict[str, type[BaseTransport]] = {
    "websocket": WebSocketTransport,
    "websockettransport": WebSocketTransport,
}


def resolve_transport(transport: Any = None) -> BaseTransport:
    """Resolve the transport to use.

    ``transport`` may be ``None`` (fall back to the ``TRANSPORT`` env var,
    defaulting to ``websocket``), a :class:`BaseTransport` instance, a
    :class:`BaseTransport` subclass, or a registered transport name.
    """
    if transport is None:
        transport = os.environ.get(TRANSPORT_ENV, DEFAULT_TRANSPORT)
    if isinstance(transport, BaseTransport):
        return transport
    if isinstance(transport, type) and issubclass(transport, BaseTransport):
        return transport()
    if isinstance(transport, str):
        name = transport.lower()
        if name not in TRANSPORT_REGISTRY:
            known = sorted(TRANSPORT_REGISTRY)
            raise ValueError(
                f"unknown transport {transport!r}; known transports: {known}"
            )
        return TRANSPORT_REGISTRY[name]()
    raise TypeError(f"invalid transport: {transport!r}")


class NotificationServer:
    """Async notification server managing thread-safe registries.

    The server works with any :class:`BaseTransport`; the transport is
    responsible for accepting connections and delivering messages while the
    server owns the core notification logic (message routing, channels,
    persistence, and the Redis backbone).

    The server can optionally use Redis pub/sub as its message backbone. When a
    Redis backend is configured (``start()`` is called), inbound messages are
    published to Redis channels and a background worker subscribes to Redis and
    delivers messages to locally connected clients. This lets multiple server
    instances share a single Redis backbone and cross-deliver messages.

    Client connection state (which clients are connected, and which channels
    they subscribe to) is mirrored into Redis so that it survives a server
    restart.
    """

    def __init__(
        self,
        redis_url: Optional[str] = None,
        database_url: Optional[str] = None,
        redis_client: Any = None,
        transport: Any = None,
        rate_limit: Optional[int] = None,
        message_ttl_days: Optional[int] = None,
    ) -> None:
        self.transport = resolve_transport(transport)
        self.transport.server = self
        self.registry = ClientRegistry()
        self.channels = ChannelRegistry()
        self.store = MessageStore(database_url or DATABASE_URL)
        self.redis_url = redis_url if redis_url is not None else REDIS_URL
        self.instance_id = str(uuid.uuid4())
        self._redis_client = redis_client
        self._redis: Any = None
        self._pubsub: Any = None
        self._worker_task: Optional[asyncio.Task] = None
        self._cleanup_task: Optional[asyncio.Task] = None
        self._redis_connected = False
        self.rate_limit = rate_limit if rate_limit is not None else RATE_LIMIT
        self.message_ttl_days = (
            message_ttl_days if message_ttl_days is not None else MESSAGE_TTL_DAYS
        )
        self._rate_counters: dict[str, list[float]] = {}
        self._rate_lock = threading.Lock()

    # ── Lifecycle ──────────────────────────────────────────────

    @property
    def redis_connected(self) -> bool:
        return self._redis_connected

    @property
    def handler(self) -> Callable[[Any], Awaitable[None]]:
        """Connection handler provided by the active transport."""
        return self.transport.handler

    async def start(self) -> None:
        """Connect to Redis (if configured) and start the delivery worker.

        Also performs an initial message-expiry cleanup pass and schedules a
        background cleanup task.
        """
        if not self._redis_connected:
            if self._redis_client is not None:
                self._redis = self._redis_client
                self._redis_connected = True
            elif self.redis_url:
                from redis import asyncio as aioredis

                self._redis = aioredis.from_url(self.redis_url, decode_responses=True)
                self._redis_connected = True
            if self._redis_connected:
                self._pubsub = self._redis.pubsub()
                await self._pubsub.psubscribe(REDIS_SUBSCRIBE_PATTERN)
                self._worker_task = asyncio.create_task(self._run_worker())
        self.cleanup_expired()
        if self._cleanup_task is None:
            self._cleanup_task = asyncio.create_task(self._run_cleanup())

    async def stop(self) -> None:
        """Stop the worker and close the Redis connection."""
        if self._cleanup_task is not None:
            self._cleanup_task.cancel()
            try:
                await self._cleanup_task
            except (asyncio.CancelledError, Exception):
                pass
            self._cleanup_task = None
        if self._worker_task is not None:
            self._worker_task.cancel()
            try:
                await self._worker_task
            except (asyncio.CancelledError, Exception):
                pass
            self._worker_task = None
        if self._pubsub is not None:
            try:
                await self._pubsub.aclose()
            except Exception:
                pass
            self._pubsub = None
        if self._redis is not None and self._redis_client is None:
            try:
                await self._redis.aclose()
            except Exception:
                pass
        self._redis = None
        self._redis_connected = False

    # ── Redis backbone ─────────────────────────────────────────

    async def _run_worker(self) -> None:
        """Subscribe to the Redis backbone and deliver messages locally."""
        async for message in self._pubsub.listen():
            if message.get("type") != "pmessage":
                continue
            try:
                payload = json.loads(message.get("data"))
            except (TypeError, ValueError):
                continue
            if isinstance(payload, dict):
                await self._deliver_from_redis(message.get("channel"), payload)

    async def _deliver_from_redis(self, redis_channel: str, message: dict) -> None:
        msg_type = message.get("type")
        if msg_type == "broadcast":
            channel = message.get("channel")
            if channel:
                await self.publish(channel, message)
            else:
                await self.broadcast(message)
        elif msg_type == "direct":
            prefix = REDIS_PREFIX + "direct:"
            if redis_channel.startswith(prefix):
                await self.send_to(redis_channel[len(prefix):], message)

    async def _publish_to_redis(self, message: dict, target: Optional[str] = None) -> None:
        msg_type = message.get("type")
        if msg_type == "broadcast":
            channel = message.get("channel")
            redis_channel = (
                REDIS_PREFIX + "channel:" + channel if channel else REDIS_PREFIX + "broadcast"
            )
        elif msg_type == "direct":
            redis_channel = REDIS_PREFIX + "direct:" + str(target)
        else:
            return
        await self._redis.publish(redis_channel, json.dumps(message))

    async def _client_exists(self, client_id: str) -> bool:
        if self._redis_connected:
            return bool(
                await self._redis.exists(REDIS_PREFIX + "client:" + client_id)
            )
        return client_id in self.registry

    async def _register_client(self, client_id: str) -> None:
        if self._redis_connected:
            await self._redis.set(REDIS_PREFIX + "client:" + client_id, self.instance_id)

    async def _unregister_client(self, client_id: str) -> None:
        if self._redis_connected:
            await self._redis.delete(REDIS_PREFIX + "client:" + client_id)

    async def _redis_subscribe(self, client_id: str, channel: str) -> None:
        await self._redis.sadd(REDIS_PREFIX + "subscribers:" + channel, client_id)

    async def _redis_unsubscribe(self, client_id: str, channel: str) -> None:
        await self._redis.srem(REDIS_PREFIX + "subscribers:" + channel, client_id)

    # ── Rate limiting ──────────────────────────────────────────

    async def _check_rate_limit(self, client_id: str) -> bool:
        """Return ``True`` if the client is allowed to send another message.

        Enforces a per-client message-per-minute limit using Redis counters
        when a Redis backend is connected, falling back to an in-memory sliding
        window otherwise.
        """
        if not self.rate_limit or self.rate_limit <= 0:
            return True
        if self._redis_connected:
            bucket = int(time.time() // 60)
            key = f"{REDIS_PREFIX}ratelimit:{client_id}:{bucket}"
            current = await self._redis.incr(key)
            if current == 1:
                await self._redis.expire(key, 60)
            return current <= self.rate_limit

        now = time.time()
        with self._rate_lock:
            window = [t for t in self._rate_counters.get(client_id, []) if now - t < 60]
            if len(window) >= self.rate_limit:
                self._rate_counters[client_id] = window
                return False
            window.append(now)
            self._rate_counters[client_id] = window
            return True

    # ── Message expiry ─────────────────────────────────────────

    def cleanup_expired(self) -> int:
        """Delete persisted messages older than the configured TTL."""
        cutoff = datetime.now(timezone.utc) - timedelta(days=self.message_ttl_days)
        return self.store.delete_older_than(cutoff.isoformat())

    async def _run_cleanup(self) -> None:
        """Periodically delete expired messages."""
        while True:
            await asyncio.sleep(CLEANUP_INTERVAL_SECONDS)
            try:
                self.cleanup_expired()
            except Exception:
                pass

    def _persist(self, outgoing: dict) -> None:
        msg_type = outgoing.get("type") or ""
        channel = outgoing.get("channel") or ""
        payload = outgoing.get("payload")
        if not isinstance(payload, dict):
            payload = {}
        self.store.save(channel, msg_type, payload, outgoing.get("timestamp") or utc_now())

    # ── Outbound helpers ───────────────────────────────────────

    async def send_to(self, client_id: str, message: dict) -> bool:
        """Send a message to a single client. Returns True on success."""
        return await self.transport.send_message(client_id, message)

    async def broadcast(self, message: dict) -> int:
        """Send a message to every connected client.

        Returns the number of clients the message was delivered to.
        """
        return await self.transport.broadcast(message)

    async def publish(self, channel: str, message: dict) -> int:
        """Send a message to every subscriber of a channel.

        Returns the number of clients the message was delivered to.
        """
        subscribers = self.channels.subscribers(channel)
        results = await asyncio.gather(
            *(self.transport.send_message(client_id, message) for client_id in subscribers),
            return_exceptions=True,
        )
        return sum(1 for ok in results if ok is True)

    # ── Inbound handling ───────────────────────────────────────

    async def _handle_message(self, sender_id: str, message: dict) -> None:
        if not await self._check_rate_limit(sender_id):
            await self.send_to(
                sender_id,
                {
                    "type": "system",
                    "payload": {
                        "error": "rate limit exceeded",
                    },
                    "timestamp": utc_now(),
                },
            )
            return

        msg_type = message.get("type")
        payload = message.get("payload") if isinstance(message.get("payload"), dict) else {}

        if msg_type == "broadcast":
            outgoing = {
                "type": "broadcast",
                "payload": payload,
                "timestamp": utc_now(),
            }
            channel = get_channel(message)
            if isinstance(channel, str) and channel:
                outgoing["channel"] = channel
            self._persist(outgoing)
            if self._redis_connected:
                await self._publish_to_redis(outgoing)
            elif isinstance(channel, str) and channel:
                await self.publish(channel, outgoing)
            else:
                await self.broadcast(outgoing)

        elif msg_type == "subscribe":
            channel = get_channel(message)
            if not isinstance(channel, str) or not channel:
                await self.send_to(
                    sender_id,
                    {
                        "type": "system",
                        "payload": {"error": "subscribe requires a channel name"},
                        "timestamp": utc_now(),
                    },
                )
                return
            self.channels.subscribe(sender_id, channel)
            if self._redis_connected:
                await self._redis_subscribe(sender_id, channel)

        elif msg_type == "unsubscribe":
            channel = get_channel(message)
            if not isinstance(channel, str) or not channel:
                await self.send_to(
                    sender_id,
                    {
                        "type": "system",
                        "payload": {"error": "unsubscribe requires a channel name"},
                        "timestamp": utc_now(),
                    },
                )
                return
            self.channels.unsubscribe(sender_id, channel)
            if self._redis_connected:
                await self._redis_unsubscribe(sender_id, channel)

        elif msg_type == "direct":
            target = payload.get("to")
            if target is None or not isinstance(target, str):
                await self.send_to(
                    sender_id,
                    {
                        "type": "system",
                        "payload": {"error": "direct message requires payload['to']"},
                        "timestamp": utc_now(),
                    },
                )
                return
            outgoing = {
                "type": "direct",
                "payload": {"from": sender_id, "message": payload.get("message")},
                "timestamp": utc_now(),
            }
            self._persist(outgoing)
            if self._redis_connected:
                if not await self._client_exists(target):
                    await self.send_to(
                        sender_id,
                        {
                            "type": "system",
                            "payload": {"error": f"target client {target!r} not connected"},
                            "timestamp": utc_now(),
                        },
                    )
                    return
                await self._publish_to_redis(outgoing, target=target)
            else:
                delivered = await self.send_to(target, outgoing)
                if not delivered:
                    await self.send_to(
                        sender_id,
                        {
                            "type": "system",
                            "payload": {"error": f"target client {target!r} not connected"},
                            "timestamp": utc_now(),
                        },
                    )

        else:
            await self.send_to(
                sender_id,
                {
                    "type": "system",
                    "payload": {
                        "error": f"unsupported message type {msg_type!r}; "
                        f"expected one of {SUPPORTED_TYPES}",
                    },
                    "timestamp": utc_now(),
                },
            )

    # ── REST endpoints ─────────────────────────────────────────

    def _json_response(self, connection: ServerConnection, status: int, data: Any) -> Any:
        body = json.dumps(data)
        response = connection.respond(status, body)
        response.headers.pop("Content-Type")
        response.headers["Content-Type"] = "application/json; charset=utf-8"
        return response

    async def process_request(
        self, connection: ServerConnection, request: Any
    ) -> Any:
        """Serve REST endpoints over plain HTTP, otherwise allow the WS handshake."""
        path = request.path
        route_path = urlsplit(path).path

        if route_path == "/health":
            return self._json_response(
                connection, 200, {"connected_clients": self.registry.count()}
            )

        if route_path == "/channels":
            return self._json_response(connection, 200, self.channels.counts())

        if route_path.startswith("/channels/") and route_path.endswith("/subscribers"):
            name = unquote(route_path[len("/channels/"):-len("/subscribers")])
            return self._json_response(
                connection, 200, self.channels.subscribers(name)
            )

        if route_path == "/messages":
            params = dict(parse_qsl(urlsplit(path).query))
            try:
                limit = int(params.get("limit", DEFAULT_LIMIT))
            except (TypeError, ValueError):
                limit = DEFAULT_LIMIT
            try:
                offset = int(params.get("offset", 0))
            except (TypeError, ValueError):
                offset = 0
            return self._json_response(
                connection, 200, self.store.list(limit=limit, offset=offset)
            )

        if route_path == "/history":
            params = self._parse_query(urlsplit(path).query)
            channel = params.get("channel")
            since = params.get("since")
            try:
                limit = int(params.get("limit", DEFAULT_LIMIT))
            except (TypeError, ValueError):
                limit = DEFAULT_LIMIT
            messages, has_more = self.store.history(
                channel=channel, since=since, limit=limit
            )
            return self._json_response(
                connection, 200, {"messages": messages, "has_more": has_more}
            )

        return None

    @staticmethod
    def _parse_query(query: str) -> dict[str, str]:
        """Parse a query string, preserving ``+`` (unlike ``parse_qsl``)."""
        result: dict[str, str] = {}
        if not query:
            return result
        for part in query.split("&"):
            if "=" in part:
                key, _, value = part.partition("=")
                result[unquote(key)] = unquote(value)
        return result


def create_server(
    app: NotificationServer,
    host: str = DEFAULT_HOST,
    port: int = DEFAULT_PORT,
) -> Callable[[], Awaitable[Any]]:
    """Return an async server factory bound to ``app`` (delegated to its transport)."""
    return app.transport.create_server(host, port)


async def main(host: str = DEFAULT_HOST, port: int = DEFAULT_PORT) -> None:
    app = NotificationServer()
    await app.start()
    try:
        async with app.transport.create_server(host, port):
            await asyncio.Future()  # run forever
    finally:
        await app.stop()


if __name__ == "__main__":
    asyncio.run(main())
