"""Tests for the published website-data reader (``apps/control_room/services/published.py``).

The EPM/energy/E_x scenario surfaces read the generated site data as their single published
source. The reader is strict: a missing file, a non-Dynamics file, or malformed JSON raises a
named error the service degrades on — never a silent empty scenario. When the real tracked
``apps/website/data.js`` is present, it parses end-to-end.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parent.parent
for _path in (_ROOT, _ROOT / "src"):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

from apps.control_room.services.published import (  # noqa: E402
    PublishedDataError,
    load_published_data,
)


def test_reads_the_generated_assignment_shape(tmp_path):
    path = tmp_path / "data.js"
    path.write_text(
        "/* Generated by build_data.py */\n"
        "window.DYNAMICS_DATA = {\n"
        '  "_meta": {"generated_at": "2026-09-12T00:00:00+00:00"},\n'
        '  "design_parameters": {"beta": 0.8}\n'
        "};\n"
    )
    payload = load_published_data(path)
    assert payload["_meta"]["generated_at"] == "2026-09-12T00:00:00+00:00"
    assert payload["design_parameters"]["beta"] == 0.8


def test_rejects_a_file_that_is_not_the_published_data(tmp_path):
    path = tmp_path / "other.js"
    path.write_text("window.SOMETHING_ELSE = {};\n")
    with pytest.raises(PublishedDataError, match="not the published Dynamics data file"):
        load_published_data(path)


def test_rejects_malformed_json(tmp_path):
    path = tmp_path / "data.js"
    path.write_text("window.DYNAMICS_DATA = {not json};\n")
    with pytest.raises(PublishedDataError, match="not valid JSON"):
        load_published_data(path)


def test_missing_file_is_a_named_error(tmp_path):
    with pytest.raises(PublishedDataError, match="unreadable"):
        load_published_data(tmp_path / "nope.js")


def test_the_tracked_site_data_parses_end_to_end():
    """The one real integration: the tracked generated file must satisfy the reader."""
    path = _ROOT / "apps" / "website" / "data.js"
    if not path.is_file():  # pragma: no cover - the file is tracked; guard for odd checkouts
        pytest.skip("apps/website/data.js not present")
    payload = load_published_data(path)
    assert "_meta" in payload
    assert "external_sources" in payload or "design_parameters" in payload
