"""``taskman`` — a tiny, pure-Python, stdlib-only task manager.

The public surface is :class:`TaskManager`.  A task carries an autogenerated
unique id, a ``todo``/``doing``/``done`` lifecycle, a priority in ``1..5``,
free-form tags, dependency edges to other tasks, and an optional ISO-8601 due
timestamp.  Dependency edges drive :meth:`TaskManager.ready_tasks`, and the
whole board round-trips through JSON via :meth:`TaskManager.save` /
:meth:`TaskManager.load`.

The package depends only on the Python standard library.
"""

from __future__ import annotations

from .manager import TaskManager

__all__ = ["TaskManager"]
