"""The :class:`TaskManager` implementation.

This module owns every behaviour the contract test exercises. The guiding
principle is **validate-before-mutate**: a call that raises must leave the
manager exactly as it found it. In practice that means each mutating method
computes and checks its full new state first, and only then writes it back.

Task record shape (a plain ``dict`` — see the package docstring for why)::

    {
        "id":         "<uuid4 hex>",   # unique, generated by add_task
        "title":      "write docs",
        "status":     "todo" | "doing" | "done",
        "priority":   1..5,            # 5 is most important
        "tags":       ["infra", ...],
        "depends_on": ["<id>", ...],   # edges to OTHER tasks
        "due_at":     "<iso-8601>" | None,
        "created_at": "<iso-8601>",    # stamped once, on creation
    }
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone

#: The only statuses a task may hold. Kept as a tuple (ordered, hashable) so the
#: error message can list the legal values in a stable order.
VALID_STATUSES = ("todo", "doing", "done")

#: Lowest and highest legal priorities (inclusive). Priority 5 is the most urgent.
MIN_PRIORITY = 1
MAX_PRIORITY = 5

#: The only fields ``update_task`` will accept. Anything else is a programming
#: error and raises ``TypeError`` rather than silently creating a junk key.
UPDATABLE_FIELDS = frozenset({"title", "priority", "tags", "depends_on", "due_at", "status"})


def _now_iso() -> str:
    """Return the current UTC instant as an ISO-8601 string.

    We use an explicit ``timezone.utc`` rather than a naive ``datetime.now()`` so
    the embedded timezone offset makes the timestamp unambiguous and JSON-stable
    across machines.
    """
    return datetime.now(timezone.utc).isoformat()


def _copy_task(task: dict) -> dict:
    """Return a shallow copy of *task* with fresh mutable containers.

    ``get_task`` hands records to callers; without this copy a caller could append
    to the returned ``tags`` list and silently mutate the manager's internal state.
    """
    copied = dict(task)
    copied["tags"] = list(task["tags"])
    copied["depends_on"] = list(task["depends_on"])
    return copied


class TaskManager:
    """An in-memory collection of tasks with dependencies, filtering and JSON persistence."""

    def __init__(self) -> None:
        # The single source of truth. Keyed by task id; insertion order is the
        # creation order that breaks priority ties in ``list_tasks``.
        self._tasks: dict[str, dict] = {}

    # ------------------------------------------------------------------ helpers

    def _require(self, task_id: str) -> dict:
        """Return the internal record for *task_id* or raise ``KeyError``.

        Centralising the lookup means every public method produces the exact same
        ``KeyError`` for an unknown id.
        """
        try:
            return self._tasks[task_id]
        except KeyError:
            raise KeyError(task_id) from None

    @staticmethod
    def _validate_priority(priority: int) -> int:
        """Validate a priority value, returning it unchanged when legal.

        ``isinstance`` is checked before the range test so a non-integer (e.g. a
        string) raises ``ValueError`` from here rather than a confusing ``TypeError``
        from the comparison. Booleans are rejected explicitly because ``True == 1``
        would otherwise slip through as priority 1.
        """
        if isinstance(priority, bool) or not isinstance(priority, int):
            raise ValueError(
                f"priority must be an int in {MIN_PRIORITY}..{MAX_PRIORITY}, got {priority!r}"
            )
        if not (MIN_PRIORITY <= priority <= MAX_PRIORITY):
            raise ValueError(
                f"priority must be in {MIN_PRIORITY}..{MAX_PRIORITY}, got {priority!r}"
            )
        return priority

    @staticmethod
    def _validate_due_at(due_at: str | None) -> str | None:
        """Validate an optional due date, returning it unchanged.

        The original string is preserved verbatim (the contract asserts an exact
        round-trip), so this checks parseability via ``datetime.fromisoformat`` but
        never normalises or reformats the input.
        """
        if due_at is None:
            return None
        if not isinstance(due_at, str):
            raise ValueError(f"due_at must be an ISO-8601 string or None, got {due_at!r}")
        try:
            datetime.fromisoformat(due_at)
        except ValueError:
            raise ValueError(f"due_at is not a parseable ISO-8601 timestamp: {due_at!r}") from None
        return due_at

    @staticmethod
    def _validate_tags(tags: list[str] | None) -> list[str]:
        """Normalise tags to a fresh list, rejecting non-list input."""
        if tags is None:
            return []
        if not isinstance(tags, (list, tuple)):
            raise ValueError(f"tags must be a list of strings, got {tags!r}")
        return list(tags)

    def _validated_dependencies(self, depends_on: list[str] | None) -> list[str]:
        """Normalise and validate a dependency list against the current task set.

        Every referenced id must already exist. Unknown ids are a ``ValueError``
        (not a ``KeyError``) because this is a validation failure in the caller's
        argument, matching the contract.
        """
        if depends_on is None:
            return []
        if not isinstance(depends_on, (list, tuple)):
            raise ValueError(f"depends_on must be a list of task ids, got {depends_on!r}")
        deps = list(depends_on)
        unknown = [dep for dep in deps if dep not in self._tasks]
        if unknown:
            raise ValueError(f"unknown dependencies: {unknown}")
        return deps

    @staticmethod
    def _detect_cycle(deps_by_id: dict[str, list[str]]) -> bool:
        """Return ``True`` if the dependency graph described by *deps_by_id* has a cycle.

        Standard three-colour depth-first search: ``visiting`` is the current DFS
        stack (a back-edge to a node on it is a cycle), ``visited`` is fully explored.
        A missing node simply ends the walk, so dangling ids cannot crash detection.

        This is deliberately a pure function over a *candidate* mapping. Mutating
        methods call it on a temporary copy before committing, which is what makes
        "cycle detection leaves state unchanged" true by construction.
        """
        visited: set[str] = set()
        visiting: set[str] = set()

        def visit(node: str) -> bool:
            if node in visiting:
                return True
            if node in visited:
                return False
            visiting.add(node)
            for dep in deps_by_id.get(node, ()):  # missing nodes resolve to no edges
                if visit(dep):
                    return True
            visiting.discard(node)
            visited.add(node)
            return False

        return any(visit(node) for node in deps_by_id)

    def _ensure_acyclic(self, deps_by_id: dict[str, list[str]]) -> None:
        """Raise ``ValueError`` if *deps_by_id* contains a cycle."""
        if self._detect_cycle(deps_by_id):
            raise ValueError("dependency cycle detected")

    # ------------------------------------------------------------------- public

    def add_task(
        self,
        title: str,
        *,
        priority: int = 3,
        tags: list[str] | None = None,
        depends_on: list[str] | None = None,
        due_at: str | None = None,
    ) -> str:
        """Create a task and return its unique id.

        All validation happens before the task is inserted, so a rejected
        ``add_task`` leaves no trace in the manager.
        """
        self._validate_priority(priority)
        self._validate_due_at(due_at)
        clean_tags = self._validate_tags(tags)
        clean_deps = self._validated_dependencies(depends_on)

        task_id = uuid.uuid4().hex
        task = {
            "id": task_id,
            "title": title,
            "status": "todo",
            "priority": priority,
            "tags": clean_tags,
            # Deduplicate while preserving the caller's order; a self-reference is
            # impossible because the fresh id did not exist when the deps were
            # validated above.
            "depends_on": list(dict.fromkeys(clean_deps)),
            "due_at": due_at,
            "created_at": _now_iso(),
        }

        # A brand-new node with edges only to pre-existing nodes cannot close a
        # cycle, but running the check keeps the invariant local and cheap.
        candidate = {tid: list(t["depends_on"]) for tid, t in self._tasks.items()}
        candidate[task_id] = task["depends_on"]
        self._ensure_acyclic(candidate)

        self._tasks[task_id] = task
        return task_id

    def get_task(self, task_id: str) -> dict:
        """Return a copy of the task record for *task_id*.

        A copy is returned so callers cannot mutate internal state by accident.
        """
        return _copy_task(self._require(task_id))

    def update_task(self, task_id: str, **fields) -> dict:
        """Update one or more fields on an existing task.

        Unknown ids raise ``KeyError``; unknown field names raise ``TypeError``.
        Every value is validated against a *candidate* record and a candidate
        dependency graph before anything is written, guaranteeing all-or-nothing
        semantics (notably for cycle rejection).
        """
        current = self._require(task_id)
        unknown = set(fields) - UPDATABLE_FIELDS
        if unknown:
            raise TypeError(f"cannot update unknown field(s): {sorted(unknown)}")

        # Build the candidate record without touching the live one.
        candidate = dict(current)
        if "title" in fields:
            candidate["title"] = fields["title"]
        if "priority" in fields:
            candidate["priority"] = self._validate_priority(fields["priority"])
        if "due_at" in fields:
            candidate["due_at"] = self._validate_due_at(fields["due_at"])
        if "tags" in fields:
            candidate["tags"] = self._validate_tags(fields["tags"])
        if "status" in fields:
            candidate["status"] = self._validate_status(fields["status"])
        if "depends_on" in fields:
            candidate["depends_on"] = list(
                dict.fromkeys(self._validated_dependencies(fields["depends_on"]))
            )

        # Validate the whole candidate graph, then commit atomically.
        candidate_graph = {tid: list(t["depends_on"]) for tid, t in self._tasks.items()}
        candidate_graph[task_id] = candidate["depends_on"]
        self._ensure_acyclic(candidate_graph)

        self._tasks[task_id] = candidate
        return _copy_task(candidate)

    def delete_task(self, task_id: str) -> None:
        """Delete *task_id*, refusing while any other task still depends on it."""
        self._require(task_id)
        dependents = [
            other["id"]
            for other in self._tasks.values()
            if other["id"] != task_id and task_id in other["depends_on"]
        ]
        if dependents:
            raise ValueError(f"task {task_id!r} is still required by {dependents}")
        del self._tasks[task_id]

    @staticmethod
    def _validate_status(status: str) -> str:
        """Return *status* if it is one of ``todo`` / ``doing`` / ``done``."""
        if status not in VALID_STATUSES:
            raise ValueError(f"status must be one of {VALID_STATUSES}, got {status!r}")
        return status

    def set_status(self, task_id: str, status: str) -> None:
        """Set a task's status; unknown ids raise ``KeyError``, bad statuses ``ValueError``."""
        self._require(task_id)
        self._tasks[task_id]["status"] = self._validate_status(status)

    def list_tasks(
        self,
        *,
        status: str | None = None,
        priority: int | None = None,
        tag: str | None = None,
    ) -> list[dict]:
        """Return tasks matching the optional filters, ordered by priority descending.

        Ties fall back to creation order because the underlying dict preserves
        insertion order and Python's sort is stable.
        """
        selected = [
            task
            for task in self._tasks.values()
            if (status is None or task["status"] == status)
            and (priority is None or task["priority"] == priority)
            and (tag is None or tag in task["tags"])
        ]
        selected.sort(key=lambda task: task["priority"], reverse=True)
        return [_copy_task(task) for task in selected]

    def ready_tasks(self) -> list[dict]:
        """Return not-done tasks whose dependencies are all done.

        Ordering mirrors ``list_tasks`` (priority descending, creation-order ties)
        for a predictable caller experience.
        """
        ready = [
            task
            for task in self._tasks.values()
            if task["status"] != "done"
            and all(
                dep in self._tasks and self._tasks[dep]["status"] == "done"
                for dep in task["depends_on"]
            )
        ]
        ready.sort(key=lambda task: task["priority"], reverse=True)
        return [_copy_task(task) for task in ready]

    # --------------------------------------------------------------- persistence

    def save(self, path: str) -> None:
        """Write the task set to *path* as JSON.

        A wrapper object (``{"tasks": [...]}``) is used rather than a bare dict so
        the file carries an explicit list with a deterministic, creation-ordered
        layout, and leaves room for future metadata without a format break.
        """
        payload = {"version": 1, "tasks": list(self._tasks.values())}
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2)

    @classmethod
    def load(cls, path: str) -> TaskManager:
        """Reconstruct a :class:`TaskManager` from a file written by :meth:`save`.

        The dict is rebuilt in file order, which preserves both the ids and their
        creation order, so ordering-dependent behaviour survives the round-trip.
        """
        with open(path, encoding="utf-8") as handle:
            payload = json.load(handle)
        manager = cls()
        for task in payload["tasks"]:
            manager._tasks[task["id"]] = task
        return manager

    def __len__(self) -> int:
        """Number of tasks currently stored (a small convenience for callers)."""
        return len(self._tasks)
