"""The canonical input resolver every publication-eligible lab must consume.

Why this module exists
----------------------
``docs/review/semantic_integrity_review.md`` P0, required correction:

    A publication lab may consume only a canonical exported table or the registry
    resolver — not ``_results_summary.json``, arbitrary result globs, or unfiltered raw
    story files.

Before this module, the seven non-quarantined labs each did their own
``Path("experiments/results/stories").glob("*.json")`` with ad-hoc filename filters
(``"log" in f.name``, ``"dvs" in f.name``). That is *unfiltered*: it picks up tombstoned
cells, superseded versions, and remediation leftovers, and it silently changes meaning
whenever a file lands in the directory. The website's main metrics did not have this
problem — ``build_data.py`` resolves them through the registry — which is exactly the
"split publication path" the review named.

This module is the shared resolver. It answers one question — *which measurement records
are canonical right now?* — from the registry in ``experiments/data_manifest.json`` (the
compacted, latest-per-entity, lifecycle-aware index generated by
``scripts/generate_manifest.py``), and hands back the joined payloads.

The rules it implements
-----------------------
1. **Only ``lifecycle_state == "current"`` rows.** Tombstoned rows (the 77 contaminated
   ``early_degrade`` story cells) and superseded versions contribute nothing.
2. **The registry chooses the files, never a glob.** A payload is read only because a
   current registry row points at it. A file nobody registered is invisible here.
3. **A missing payload contributes nothing** — never a fabricated zero.
4. **The no-op condition relabel** (``docs/data_integrity_findings.md`` treatment rule 1)
   is applied once, here, so no lab re-implements it.
5. **Identity is computed, not asserted**: :func:`manifest_identity` produces the
   ``registry_identity_sha256`` / ``registry_version`` a lab embeds in its output and
   ``build_data.py`` re-checks at publication time (see ``lab_contract``), and
   :func:`resolved_input_identity` attests to the exact payload *content*.

Why the registry-identity hash is a *projection* of the manifest, not the file's sha256
----------------------------------------------------------------------------------
Hashing ``data_manifest.json`` whole would be circular: the manifest records the sha256
of ``apps/website/data.js``, which is produced *by publishing the labs*, and it carries a
fresh ``generated_at`` on every run. A lab's embedded hash would be invalidated by the
very act of publishing it — every subsequent build would reject every lab.

So the registry-identity hash covers the manifest's **canonical-state identity**:
``schema_version`` plus the full ``registry`` array. That is precisely the *selection* a
lab consumed. It changes when records are added, superseded, or tombstoned (the lab
genuinely is stale) and does not change when the pipeline re-stamps a timestamp or
re-hashes its own output. It does **not** attest to payload *bytes* — that is what the
separate ``resolved_input_sha256`` (review P2) is for.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

#: Repo root — ``src/agentic_dynamics/reporting/canonical_corpus.py`` -> four parents up.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent

#: The compacted canonical-state registry (written by ``scripts/generate_manifest.py``).
DATA_MANIFEST_PATH = PROJECT_ROOT / "experiments" / "data_manifest.json"

RESULTS_DIR = PROJECT_ROOT / "experiments" / "results"
STORIES_DIR = RESULTS_DIR / "stories"
REVIEWS_DIR = RESULTS_DIR / "reviews"
ANALYSIS_DIR = RESULTS_DIR / "analysis"

#: Conditions that were no-ops in the pre-fix corpus (``docs/data_integrity_findings.md``
#: treatment rule 1). Mirrors ``knowledge.story_ingestion.NOOP_CONDITIONS`` and
#: ``scripts/build_data.py``'s copy — duplicated rather than imported so this module stays
#: dependency-light (importing the knowledge plane drags in the chroma/neo4j stack, which a
#: lab book must never need).
NOOP_CONDITIONS = frozenset({"early_degrade", "bad_seed"})

#: The table names a lab may request. Each maps to one resolver below.
TABLES = ("story", "review", "analysis", "finding")

#: table name -> the :class:`CanonicalTables` attribute holding its rows. Declared once so
#: callers never re-derive it (and so adding a table is a single-place change).
TABLE_ATTRIBUTES = {
    "story": "stories",
    "review": "reviews",
    "analysis": "analysis",
    "finding": "findings",
}

#: table name -> the registry ``source_type`` whose current rows *obligate* a payload.
#: ``analysis`` is absent: it is a derived join over story rows, not a registered source
#: type, so a missing analysis is not an unresolved row. This is the set the
#: :class:`ResolutionReport` counts ``expected_current``/``resolved`` over.
TABLE_SOURCE_TYPES = {"story": "story", "review": "review", "finding": "finding"}


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ManifestIdentity:
    """Who the input dataset *is* — the lineage a lab embeds and build_data re-checks.

    ``registry_identity_sha256`` is the projection hash described in the module docstring
    (``schema_version`` + the ``registry`` array — the registry identity, not the manifest
    file's bytes and not the payload bytes); ``registry_version`` is a human-readable
    version string combining the manifest schema version with the canonical row count, so a
    mismatch is legible in a log line without diffing hashes.
    """

    registry_identity_sha256: str
    registry_version: str
    n_rows: int
    n_current: int

    @classmethod
    def empty(cls) -> ManifestIdentity:
        """Identity of "no manifest" — an explicit absence, distinguishable from a real one.

        Deliberately NOT a plausible-looking hash: a lab built without a manifest must be
        rejected at publication, and an obviously-empty identity makes that unambiguous.
        """
        return cls(registry_identity_sha256="", registry_version="absent", n_rows=0, n_current=0)


def _canonical_json(obj: Any) -> bytes:
    """Stable JSON encoding for hashing: sorted keys, no incidental whitespace."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")


def read_manifest(manifest_path: Path | None = None) -> dict:
    """Load ``data_manifest.json``, degrading to ``{}`` when absent/unreadable.

    Mirrors ``scripts/registry.load_registry``'s file-fallback posture: a missing manifest
    is a *state*, not a crash. The caller (a lab) then emits an empty identity, and the
    publication gate rejects the output — the failure surfaces where it matters.
    """
    path = manifest_path or DATA_MANIFEST_PATH
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def manifest_identity(
    manifest: dict | None = None, *, manifest_path: Path | None = None
) -> ManifestIdentity:
    """Compute the canonical-state identity of a manifest.

    Pass either an already-loaded ``manifest`` dict or a path. The hash covers
    ``schema_version`` + the whole ``registry`` array (see the module docstring for why not
    the raw file bytes).
    """
    man = manifest if manifest is not None else read_manifest(manifest_path)
    rows = man.get("registry") or []
    if not man or not rows:
        return ManifestIdentity.empty()

    schema_version = str(man.get("schema_version", "unknown"))
    digest = hashlib.sha256(
        _canonical_json({"schema_version": schema_version, "registry": rows})
    ).hexdigest()
    n_current = sum(1 for r in rows if r.get("lifecycle_state") == "current")
    return ManifestIdentity(
        registry_identity_sha256=digest,
        registry_version=f"data-manifest/{schema_version}+{len(rows)}rows",
        n_rows=len(rows),
        n_current=n_current,
    )


def current_manifest_identity(manifest_path: Path | None = None) -> ManifestIdentity:
    """Identity of the manifest on disk right now — build_data's side of the comparison."""
    return manifest_identity(manifest_path=manifest_path)


#: The data-integrity policy version (public-truth review P1/P2). Bumped when the treatment
#: rules in ``docs/data_integrity_findings.md`` change (e.g. the no-op condition relabel), so
#: a policy change is visible in the publication contract even when the measured bytes do not.
DATA_INTEGRITY_POLICY_VERSION = "data-integrity/v1"

#: The normalization/reducer policy version (public-truth review P1/P2). Bumped when the
#: canonical projection of a resolved payload changes meaning — the no-op condition relabel,
#: or the set of measured values analyses consume. Folded into ``resolved_input_identity`` so
#: a normalization-policy change moves the hash even when every payload byte is identical.
NORMALIZATION_VERSION = "canonical-projection/v2"

#: Resolver provenance/join keys that are NOT measured content and must not enter the content
#: projection. Excluded by name — deliberately, not by a blanket "underscore = private" rule —
#: so a *future* derived semantic field (like ``_canonical_condition``) is included unless it
#: is added here. ``_source_path`` is an absolute path (environment-dependent); ``_registry``
#: is the provenance block already folded into the resolved identity; ``_story_id`` is the
#: review/analysis join key; ``_experiment`` is the finding's parent-file provenance.
_PROVENANCE_KEYS = frozenset({"_source_path", "_registry", "_story_id", "_experiment"})


def _payload_projection(payload: dict) -> dict:
    """The canonical semantic projection of a resolved payload (public-truth P1/P2).

    Includes the measured values analyses consume (everything that is NOT named in
    :data:`_PROVENANCE_KEYS`) **and** the derived semantic field ``_canonical_condition`` —
    the no-op relabel, exactly the field a normalization-policy change mutates. The pre-p5
    filter ("everything except underscore keys") dropped ``_canonical_condition``, so a
    normalization change left ``resolved_input_sha256`` unchanged while the effective
    analysis population changed; this projection closes that gap.
    """
    return {k: v for k, v in payload.items() if k not in _PROVENANCE_KEYS}


def resolved_input_identity(tables: CanonicalTables, *, waiver_digest: str | None = None) -> str:
    """``sha256`` over the canonical semantic projection (public-truth review P1/P2).

    The projection is deliberately defined, not "everything except underscore keys". It
    folds in three kinds of thing:

    * per resolved payload, keyed by its resolved identity ``(table, entity_id,
      knowledge_id)``: the content digest of :func:`_payload_projection` — the measured
      values **plus** the canonical condition;
    * the normalization/reducer policy version (:data:`NORMALIZATION_VERSION`);
    * the waiver-set digest (:func:`waiver_set_digest`).

    So the hash moves when (a) a payload's measured bytes change, (b) the no-op relabel
    reclassifies a cell (``_canonical_condition``), (c) the normalization policy is bumped,
    or (d) the waiver set changes — but NOT when only environment-dependent provenance
    (``_source_path``) changes. ``build_contract`` embeds it as ``resolved_input_sha256``;
    ``validate_contract`` recomputes it the same way and rejects a drift.
    """
    digest = waiver_digest if waiver_digest is not None else waiver_set_digest()
    rows: list[tuple] = []
    for table in tables.tables:
        attr = TABLE_ATTRIBUTES.get(table)
        if attr is None:
            continue
        for payload in getattr(tables, attr):
            reg = payload.get("_registry") or {}
            content_digest = hashlib.sha256(
                _canonical_json(_payload_projection(payload))
            ).hexdigest()
            rows.append(
                (
                    table,
                    str(reg.get("entity_id") or ""),
                    str(reg.get("knowledge_id") or ""),
                    content_digest,
                )
            )
    rows.sort()
    projection = {
        "normalization_version": NORMALIZATION_VERSION,
        "waiver_digest": digest,
        "payloads": rows,
    }
    return hashlib.sha256(_canonical_json(projection)).hexdigest()


# ---------------------------------------------------------------------------
# Resolution completeness (review P1)
# ---------------------------------------------------------------------------

#: The committed waiver artifact — the reason-bearing exemptions for current registry rows
#: that cannot resolve to a payload (the 10 known payload-less story rows).
DEFAULT_WAIVER_PATH = PROJECT_ROOT / "experiments" / "waivers" / "unresolved_payloads.json"

#: The reasons a current row can fail to resolve. ``duplicate`` is a registry-level defect
#: (two current rows share a logical locator); the rest are payload-join failures.
UNRESOLVED_KINDS = ("missing", "unreadable", "ambiguous", "duplicate")


@dataclass(frozen=True)
class ResolutionIssue:
    """One current registry row that did not resolve to a measurement payload.

    ``kind`` is one of :data:`UNRESOLVED_KINDS`:

    * ``missing`` — no payload file exists for the row (or, for a ``finding``, the row's
      named run is absent from its aggregate file);
    * ``unreadable`` — the payload file exists but is not valid JSON;
    * ``ambiguous`` — more than one payload file matches the row's locator;
    * ``duplicate`` — two current rows share a logical locator (the duplicate is dropped).

    A row with a ``missing``/``unreadable``/``ambiguous`` payload must be either fixed or
    waived before publication; a ``duplicate`` is a manifest defect to repair.
    """

    table: str
    entity_id: str | None
    logical_locator: str
    source_uri: str | None
    kind: str


@dataclass(frozen=True)
class ResolutionReport:
    """How completely the current registry resolved to measurement payloads.

    The six fields are exactly the review's P1 vocabulary:
    ``expected_current`` (current rows), ``resolved`` (payloads produced), and the four
    failure kinds. ``issues`` carries one :class:`ResolutionIssue` per unresolved row so a
    caller can fail closed, and can match each issue against a reason-bearing waiver.
    """

    expected_current: int = 0
    resolved: int = 0
    missing: int = 0
    unreadable: int = 0
    ambiguous: int = 0
    duplicate: int = 0
    issues: tuple[ResolutionIssue, ...] = ()

    @property
    def unresolved(self) -> int:
        """Every unresolved row, regardless of kind."""
        return self.missing + self.unreadable + self.ambiguous + self.duplicate

    @property
    def complete(self) -> bool:
        """True when every expected current row produced a payload."""
        return self.unresolved == 0

    def by_kind(self, kind: str) -> list[ResolutionIssue]:
        """The issues of one failure kind, in resolution order."""
        return [i for i in self.issues if i.kind == kind]

    @classmethod
    def from_issues(
        cls, expected_current: int, resolved: int, issues: list[ResolutionIssue]
    ) -> ResolutionReport:
        """Build a report from its raw ingredients (tallies the four failure kinds)."""
        from collections import Counter

        kinds = Counter(i.kind for i in issues)
        return cls(
            expected_current=expected_current,
            resolved=resolved,
            missing=kinds.get("missing", 0),
            unreadable=kinds.get("unreadable", 0),
            ambiguous=kinds.get("ambiguous", 0),
            duplicate=kinds.get("duplicate", 0),
            issues=tuple(issues),
        )

    @classmethod
    def empty(cls) -> ResolutionReport:
        """The report of "no manifest" — an explicit absence, like :meth:`ManifestIdentity.empty`."""
        return cls()


@dataclass(frozen=True)
class Waiver:
    """One hard-bound, *temporary* exemption for an unresolved current row.

    ``logical_locator`` + ``issue_kind`` name *which* unresolved problem is excused (a
    broad ``(table, locator)`` key would let a future, different problem at the same
    locator inherit an old waiver — public-truth review P1). ``entity_id``/``knowledge_id``/
    ``source_uri`` are carried for auditability, ``reason``/``review_by`` are required
    non-empty, and ``expiry`` is the deadline after which the waiver is no longer accepted
    (a waiver is an operational exception, never a permanent "this locator is fine" marker).
    """

    table: str
    logical_locator: str
    issue_kind: str
    entity_id: str | None
    knowledge_id: str | None
    source_uri: str | None
    reason: str
    review_by: str
    expiry: str

    @property
    def key(self) -> tuple[str, str, str]:
        """The ``(table, logical_locator, issue_kind)`` identity a waiver is matched on."""
        return (self.table, self.logical_locator, self.issue_kind)


def load_waivers(path: Path | None = None) -> list[Waiver]:
    """Load the committed waiver artifact, degrading to ``[]`` when absent/unreadable.

    Each entry must carry the hard-bound fields (a non-empty ``reason``/``review_by``/
    ``expiry`` and a recognised ``issue_kind``); an entry missing one is skipped — the same
    file-fallback posture as :func:`read_manifest`: a malformed waiver is a *state* (no
    exemption claimed), not a crash, and the caller's fail-closed check then rejects the
    unresolved row, which is the safe default.
    """
    waiver_path = path or DEFAULT_WAIVER_PATH
    if not waiver_path.exists():
        return []
    try:
        raw = json.loads(waiver_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []
    waivers = []
    for entry in raw.get("waivers") or []:
        reason = str(entry.get("reason") or "").strip()
        review_by = str(entry.get("review_by") or "").strip()
        expiry = str(entry.get("expiry") or "").strip()
        issue_kind = str(entry.get("issue_kind") or "")
        if not reason or not review_by or not expiry:
            continue  # a hard-bound field is missing — not a waiver
        if issue_kind not in UNRESOLVED_KINDS:
            continue  # an unknown issue kind can never match a real resolution issue
        waivers.append(
            Waiver(
                table=str(entry.get("table") or ""),
                logical_locator=str(entry.get("logical_locator") or ""),
                issue_kind=issue_kind,
                entity_id=entry.get("entity_id"),
                knowledge_id=entry.get("knowledge_id"),
                source_uri=entry.get("source_uri"),
                reason=reason,
                review_by=review_by,
                expiry=expiry,
            )
        )
    return waivers


def waiver_set_digest(waivers: list[Waiver] | None = None) -> str:
    """``sha256`` of the canonical waiver set (public-truth review P1/P2).

    A waiver-set change must move ``resolved_input_identity``: the effective analysis
    population changes with the waiver set even when every payload is byte-identical. The
    digest covers each hard-bound waiver's full identity in canonical sorted order, so an
    edit to a reason, a reviewer, an expiry, or the set itself all change it.
    """
    waivers = load_waivers() if waivers is None else waivers
    rows = [
        (
            w.table,
            w.logical_locator,
            w.issue_kind,
            w.entity_id,
            w.knowledge_id,
            w.source_uri,
            w.reason,
            w.review_by,
            w.expiry,
        )
        for w in waivers
    ]
    rows.sort()
    return hashlib.sha256(_canonical_json(rows)).hexdigest()


def _waiver_key(table: str, logical_locator: str, issue_kind: str) -> tuple[str, str, str]:
    """The row identity a waiver is matched on: ``(table, logical_locator, issue_kind)``.

    ``logical_locator`` is unique within a table (it *is* the story id for ``story``), and
    ``issue_kind`` narrows the key to the *specific* unresolved problem, so a "missing"
    waiver can never silently cover a future "unreadable" defect at the same locator.
    """
    return (table, logical_locator, issue_kind)


def _is_expired(waiver: Waiver, now: datetime) -> bool:
    """True when ``waiver.expiry`` is at or before ``now`` (a waiver is temporary).

    An unparseable expiry is treated as expired — a waiver must state a real deadline, not
    an opaque string that never lapses.
    """
    try:
        exp = datetime.fromisoformat(waiver.expiry)
        if exp.tzinfo is None:
            exp = exp.replace(tzinfo=timezone.utc)
        return exp <= now
    except ValueError:
        return True


def validate_waivers(
    report: ResolutionReport, waivers: list[Waiver]
) -> tuple[list[Waiver], list[str]]:
    """Return ``(valid, rejected)`` — reject stale, duplicate, and unmatched waivers.

    The three rejection classes (public-truth review P1, phase p4):

    * **stale** — ``expiry`` has already passed;
    * **duplicate** — two waivers share the same ``(table, logical_locator, issue_kind)``;
    * **unmatched** — the waiver's key names no unresolved issue in ``report`` (its row was
      fixed or tombstoned since the waiver was written, so the waiver is dead).

    A rejected waiver is *not* applied; its reason string is returned so the caller can
    surface the defect instead of silently dropping the coverage it thought it had.
    """
    now = datetime.now(timezone.utc)
    valid: list[Waiver] = []
    rejected: list[str] = []
    seen: set[tuple[str, str, str]] = set()
    issue_keys = {(i.table, i.logical_locator, i.kind) for i in report.issues}

    for w in waivers:
        if _is_expired(w, now):
            rejected.append(
                f"stale waiver {w.table}/{w.logical_locator} ({w.issue_kind}): "
                f"expiry {w.expiry!r} has passed"
            )
            continue
        if w.key in seen:
            rejected.append(f"duplicate waiver {w.table}/{w.logical_locator} ({w.issue_kind})")
            continue
        if w.key not in issue_keys:
            rejected.append(
                f"unmatched waiver {w.table}/{w.logical_locator} ({w.issue_kind}): "
                f"no such unresolved row"
            )
            continue
        seen.add(w.key)
        valid.append(w)

    return valid, rejected


def unwaivered_issues(report: ResolutionReport, waivers: list[Waiver]) -> list[ResolutionIssue]:
    """The unresolved rows *not* covered by a valid waiver — the fail-closed trigger.

    A waiver covers an issue when its ``(table, logical_locator, issue_kind)`` matches.
    Everything else — missing, unreadable, ambiguous, duplicate — is a publication-blocking
    defect unless a valid waiver covers it.
    """
    waived = {w.key for w in waivers}
    return [i for i in report.issues if (i.table, i.logical_locator, i.kind) not in waived]


# ---------------------------------------------------------------------------
# Row selection + payload joins
# ---------------------------------------------------------------------------


def registry_rows(manifest: dict) -> list[dict]:
    """The manifest's ``registry`` array (``[]`` when absent)."""
    return list(manifest.get("registry") or [])


def current_rows(manifest: dict, source_type: str) -> list[dict]:
    """Every ``lifecycle_state == "current"`` row of one ``source_type``.

    This single filter is what makes a lab's input canonical: tombstoned and superseded
    records never reach a measurement.
    """
    return [
        r
        for r in registry_rows(manifest)
        if r.get("source_type") == source_type and r.get("lifecycle_state") == "current"
    ]


def effective_story_condition(payload: dict) -> str:
    """A story's condition with the no-op relabel applied.

    ``docs/data_integrity_findings.md`` treatment rule 1: a story labelled
    ``early_degrade``/``bad_seed`` that carries no instrumented verdict
    (``test_executed_success`` is not a bool — the pre-fix cells never ran the independent
    test runner) received no actual perturbation, so its condition is corrected to
    ``clean``. Its cost and quality measurements stay valid; only the label was wrong.
    """
    condition = str(payload.get("perturbation_condition") or "")
    if condition in NOOP_CONDITIONS and not isinstance(payload.get("test_executed_success"), bool):
        return "clean"
    # An absent/empty label (the pre-fix cells whose filenames never carried a
    # condition) is also "no perturbation applied" — fold it into ``clean`` so every
    # ``_canonical_condition`` is a real, publication-legal condition name rather than an
    # empty string that a consumer would have to re-normalize (``lab_condition_effects.py``
    # previously had to do ``or "clean"`` itself, which is how the split silently drifted).
    if not condition:
        return "clean"
    return condition


def _read_json(path: Path) -> dict | None:
    """Read one payload, returning ``None`` (never a fabricated stub) on any failure."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _story_paths(story_id: str) -> list[Path]:
    """Locate a story payload from its id (top-level only — never remediation subdirs).

    Story result filenames end in ``_<story_id>.json`` (``story.save_story_result``), and a
    ``story`` registry row's ``logical_locator`` *is* that id. Scoped to ``STORIES_DIR``'s
    top level, so remediation subdirectories (``stories/_remediation_contaminated/``) can
    never be picked up. Returns *all* matches so the caller can flag an ambiguous join.
    """
    if not story_id:
        return []
    return sorted(p for p in STORIES_DIR.glob(f"*_{story_id}.json") if p.is_file())


def _issue(table: str, row: dict, kind: str, *, story_id: str | None = None) -> ResolutionIssue:
    """Build a :class:`ResolutionIssue` from a registry row (locator defaults to the row's)."""
    return ResolutionIssue(
        table=table,
        entity_id=row.get("entity_id"),
        logical_locator=str(story_id if story_id is not None else row.get("logical_locator") or ""),
        source_uri=row.get("source_uri"),
        kind=kind,
    )


def _duplicate_issues(rows: list[dict], table: str) -> list[ResolutionIssue]:
    """A ``duplicate`` issue for every current row that shares its locator with another.

    Two current rows naming the same logical locator is a manifest defect (one of them is
    stale and should have been superseded/tombstoned, not left current). The resolver still
    joins both — this only *flags* the defect so publication can fail closed on it.
    """
    seen: set[str] = set()
    issues: list[ResolutionIssue] = []
    for row in rows:
        loc = str(row.get("logical_locator") or "")
        if not loc:
            continue  # an empty locator is a "missing" failure, not a duplicate
        if loc in seen:
            issues.append(_issue(table, row, "duplicate"))
        else:
            seen.add(loc)
    return issues


def resolve_stories(manifest: dict) -> tuple[list[dict], list[ResolutionIssue]]:
    """Every current ``story`` payload, condition-corrected and provenance-stamped.

    Each payload gains three underscore-prefixed keys so downstream labs never have to
    re-derive provenance:

    * ``_canonical_condition`` — the relabelled condition (use this, not the raw field)
    * ``_registry`` — ``{entity_id, knowledge_id, source_uri, lifecycle_state}``
    * ``_source_path`` — the resolved payload path, for a lab that needs the typed
      ``runtime.story.load_story_result`` loader rather than the raw dict. It is a
      *resolved* path (the registry chose it), so using it is still canonical.

    Returns ``(payloads, issues)`` — an issue for every current row whose payload is
    missing, unreadable, or ambiguous (see :class:`ResolutionReport`).
    """
    out: list[dict] = []
    issues: list[ResolutionIssue] = []
    for row in current_rows(manifest, "story"):
        story_id = str(row.get("logical_locator") or "")
        matches = _story_paths(story_id)
        if not story_id or not matches:
            issues.append(_issue("story", row, "missing", story_id=story_id))
            continue
        if len(matches) > 1:
            issues.append(_issue("story", row, "ambiguous", story_id=story_id))
            continue
        payload = _read_json(matches[0])
        if payload is None:
            issues.append(_issue("story", row, "unreadable", story_id=story_id))
            continue
        payload["_canonical_condition"] = effective_story_condition(payload)
        payload["_source_path"] = str(matches[0])
        payload["_registry"] = {
            "entity_id": row.get("entity_id"),
            "knowledge_id": row.get("knowledge_id"),
            "source_uri": row.get("source_uri"),
            "lifecycle_state": row.get("lifecycle_state"),
        }
        payload.setdefault("story_id", story_id)
        out.append(payload)
    return out, issues


def resolve_reviews(manifest: dict) -> tuple[list[dict], list[ResolutionIssue]]:
    """Every current ``review`` payload.

    A ``review`` row's ``logical_locator`` is the story id, and the reviewer writes
    ``reviews/review_<story_id>.json`` (``scripts/finalize_reviews.py``). The payload gains
    ``_story_id`` so a lab can join reviews to stories without re-parsing file names.

    Returns ``(payloads, issues)`` — a current review row whose file is absent or unreadable
    is an unresolved row.
    """
    out: list[dict] = []
    issues: list[ResolutionIssue] = []
    for row in current_rows(manifest, "review"):
        story_id = str(row.get("logical_locator") or "")
        path = REVIEWS_DIR / f"review_{story_id}.json"
        if not path.exists():
            issues.append(_issue("review", row, "missing"))
            continue
        payload = _read_json(path)
        if payload is None:
            issues.append(_issue("review", row, "unreadable"))
            continue
        payload["_story_id"] = story_id
        payload["_registry"] = {
            "entity_id": row.get("entity_id"),
            "knowledge_id": row.get("knowledge_id"),
            "source_uri": row.get("source_uri"),
            "lifecycle_state": row.get("lifecycle_state"),
        }
        out.append(payload)
    return out, issues


def resolve_analysis(manifest: dict) -> tuple[list[dict], list[ResolutionIssue]]:
    """Post-hoc analysis payloads for the current stories only.

    Analysis artifacts (``analysis/analysis_<story_id>.json``, written by
    ``scripts/analysis_worker.py``) are *derived* from a story and are not registered as
    their own ``source_type``. They are still canonical inputs here because the **story
    registry decides which ones exist**: an analysis whose story is tombstoned or
    unregistered is never read. That is the difference between a registry-filtered join
    and the ``glob("*.json")`` this module replaces.

    Returns ``(payloads, [])`` — analysis is a best-effort *join*, not a 1:1 row→payload
    obligation: a current story that was never analyzed is not an unresolved row, so this
    resolver contributes no fail-closed issues.
    """
    out: list[dict] = []
    for row in current_rows(manifest, "story"):
        story_id = str(row.get("logical_locator") or "")
        path = ANALYSIS_DIR / f"analysis_{story_id}.json"
        if not story_id or not path.exists():
            continue
        payload = _read_json(path)
        if payload is None:
            continue
        payload["_story_id"] = story_id
        # Analysis is derived from a story, so its canonical entity is the story row it
        # joins onto — the provenance that ``resolved_input_identity`` folds into the
        # payload-content hash.
        payload["_registry"] = {
            "entity_id": row.get("entity_id"),
            "knowledge_id": row.get("knowledge_id"),
            "source_uri": row.get("source_uri"),
            "lifecycle_state": row.get("lifecycle_state"),
        }
        out.append(payload)
    return out, []


def _resolve_file_uri(source_uri: str) -> Path | None:
    """Resolve a ``file://`` registry ``source_uri`` to a repo-relative path.

    ``finding`` rows carry ``file://experiments/results/…`` URIs (the
    ``knowledge_ingestion.SOURCE_URI`` contract). Any other scheme (``story:``,
    ``review:``) belongs to a different resolver, so this returns ``None``.
    """
    if not source_uri or not source_uri.startswith("file://"):
        return None
    return PROJECT_ROOT / source_uri[len("file://") :]


def resolve_findings(manifest: dict) -> tuple[list[dict], list[ResolutionIssue]]:
    """Every current ``finding`` run — the single-task perturbation cells.

    A ``finding`` row points at an aggregate results file via ``source_uri`` and names the
    one cell inside it via ``logical_locator`` (== ``basename(run["workdir"])``). This is
    the corpus that carries ``perturbation_strength`` and ``operator``, which is what makes
    the formal Grit metric computable at all.

    Each returned run gains ``_registry`` provenance and ``_experiment`` (the parent file's
    experiment name). Structurally parallel to ``build_data._finding_entry_from_resolved``,
    minus that function's mapping into the retired summary's *field vocabulary* — labs want
    the measured fields under their real names.

    Returns ``(payloads, issues)`` — a current row whose file is absent/unreadable, or whose
    named run is missing/ambiguous inside the file, is an unresolved row.
    """
    out: list[dict] = []
    issues: list[ResolutionIssue] = []
    for row in current_rows(manifest, "finding"):
        path = _resolve_file_uri(str(row.get("source_uri") or ""))
        locator = str(row.get("logical_locator") or "")
        if path is None or not locator:
            issues.append(_issue("finding", row, "missing"))
            continue
        if not path.exists():
            issues.append(_issue("finding", row, "missing"))
            continue
        payload = _read_json(path)
        if payload is None:
            issues.append(_issue("finding", row, "unreadable"))
            continue
        matches = [
            run
            for run in payload.get("runs") or []
            if str(run.get("workdir") or "").rsplit("/", 1)[-1] == locator
        ]
        if len(matches) > 1:
            issues.append(_issue("finding", row, "ambiguous"))
            continue
        if not matches:
            issues.append(_issue("finding", row, "missing"))
            continue
        run = dict(matches[0])  # never mutate the shared payload
        run["_experiment"] = payload.get("experiment", "")
        run["_registry"] = {
            "entity_id": row.get("entity_id"),
            "knowledge_id": row.get("knowledge_id"),
            "source_uri": row.get("source_uri"),
            "lifecycle_state": row.get("lifecycle_state"),
        }
        out.append(run)
    return out, issues


_RESOLVERS = {
    "story": resolve_stories,
    "review": resolve_reviews,
    "analysis": resolve_analysis,
    "finding": resolve_findings,
}


# ---------------------------------------------------------------------------
# The lab-facing entry point
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CanonicalTables:
    """The resolved canonical input a lab computes over, plus its identity.

    ``tables`` records which tables were requested; it becomes part of the
    ``input_dataset_id`` so two labs reading different slices are distinguishable.
    ``resolution`` is the completeness report (review P1) — the evidence a publication
    path uses to fail closed on unresolved current rows.
    """

    identity: ManifestIdentity
    tables: tuple[str, ...] = ()
    stories: list[dict] = field(default_factory=list)
    reviews: list[dict] = field(default_factory=list)
    analysis: list[dict] = field(default_factory=list)
    findings: list[dict] = field(default_factory=list)
    resolution: ResolutionReport = field(default_factory=ResolutionReport)

    @property
    def input_dataset_id(self) -> str:
        """Stable id of the input slice, e.g. ``canonical_registry/story+review``."""
        return (
            f"canonical_registry/{'+'.join(self.tables)}" if self.tables else "canonical_registry"
        )

    @property
    def resolved_input_sha256(self) -> str:
        """The payload-content identity (review P2) — see :func:`resolved_input_identity`."""
        return resolved_input_identity(self)

    @property
    def is_empty(self) -> bool:
        """True when nothing resolved — the caller should say so rather than publish zeros."""
        return not (self.stories or self.reviews or self.analysis or self.findings)

    def stories_by_id(self) -> dict[str, dict]:
        """``story_id -> payload`` for join-style labs."""
        return {str(s.get("story_id") or ""): s for s in self.stories if s.get("story_id")}

    def rows(self, table: str) -> list[dict]:
        """Rows of one table by its *table name* (``"story"``, ``"finding"``, …).

        Saves every caller from re-deriving the name→attribute mapping
        (``"story" -> .stories``, ``"analysis" -> .analysis``), which is the kind of
        duplicated lookup that silently rots when a table is added.
        """
        attr = TABLE_ATTRIBUTES.get(table)
        if attr is None:
            raise ValueError(f"unknown canonical table {table!r}; known: {list(TABLE_ATTRIBUTES)}")
        return getattr(self, attr)


def load_canonical_tables(
    *tables: str,
    manifest_path: Path | None = None,
) -> CanonicalTables:
    """Resolve the requested canonical tables. **The only input door a lab may use.**

    ::

        tables = load_canonical_tables("story")            # story labs
        tables = load_canonical_tables("story", "review")  # join labs

    Unknown table names raise immediately — a typo must not silently yield an empty table
    that then publishes as "no effect measured".
    """
    requested = tuple(tables) or ("story",)
    unknown = [t for t in requested if t not in _RESOLVERS]
    if unknown:
        raise ValueError(f"unknown canonical table(s) {unknown}; known: {list(_RESOLVERS)}")

    manifest = read_manifest(manifest_path)
    identity = manifest_identity(manifest)

    payloads: dict[str, list[dict]] = {}
    report_issues: list[ResolutionIssue] = []
    expected_current = 0
    resolved_count = 0
    for name in requested:
        out, issues = _RESOLVERS[name](manifest)
        payloads[name] = out
        source_type = TABLE_SOURCE_TYPES.get(name)
        if source_type is None:
            continue  # analysis — a derived join, not a row→payload obligation
        report_issues.extend(issues)
        rows = current_rows(manifest, source_type)
        expected_current += len(rows)
        resolved_count += len(out)
        report_issues.extend(_duplicate_issues(rows, name))

    resolution = ResolutionReport.from_issues(expected_current, resolved_count, report_issues)

    return CanonicalTables(
        identity=identity,
        tables=requested,
        stories=payloads.get("story", []),
        reviews=payloads.get("review", []),
        analysis=payloads.get("analysis", []),
        findings=payloads.get("finding", []),
        resolution=resolution,
    )
