"""The canonical input resolver every publication-eligible lab must consume.

Why this module exists
----------------------
``docs/review/semantic_integrity_review.md`` P0, required correction:

    A publication lab may consume only a canonical exported table or the registry
    resolver — not ``_results_summary.json``, arbitrary result globs, or unfiltered raw
    story files.

Before this module, the seven non-quarantined labs each did their own
``Path("experiments/results/stories").glob("*.json")`` with ad-hoc filename filters
(``"log" in f.name``, ``"dvs" in f.name``). That is *unfiltered*: it picks up tombstoned
cells, superseded versions, and remediation leftovers, and it silently changes meaning
whenever a file lands in the directory. The website's main metrics did not have this
problem — ``build_data.py`` resolves them through the registry — which is exactly the
"split publication path" the review named.

This module is the shared resolver. It answers one question — *which measurement records
are canonical right now?* — from the registry in ``experiments/data_manifest.json`` (the
compacted, latest-per-entity, lifecycle-aware index generated by
``scripts/generate_manifest.py``), and hands back the joined payloads.

The rules it implements
-----------------------
1. **Only ``lifecycle_state == "current"`` rows.** Tombstoned rows (the 77 contaminated
   ``early_degrade`` story cells) and superseded versions contribute nothing.
2. **The registry chooses the files, never a glob.** A payload is read only because a
   current registry row points at it. A file nobody registered is invisible here.
3. **A missing payload contributes nothing** — never a fabricated zero.
4. **The no-op condition relabel** (``docs/data_integrity_findings.md`` treatment rule 1)
   is applied once, here, so no lab re-implements it.
5. **Identity is computed, not asserted**: :func:`manifest_identity` produces the
   ``input_manifest_sha256`` / ``registry_version`` a lab embeds in its output and
   ``build_data.py`` re-checks at publication time (see ``lab_contract``).

Why the identity hash is a *projection* of the manifest, not the file's sha256
-----------------------------------------------------------------------------
Hashing ``data_manifest.json`` whole would be circular: the manifest records the sha256
of ``apps/website/data.js``, which is produced *by publishing the labs*, and it carries a
fresh ``generated_at`` on every run. A lab's embedded hash would be invalidated by the
very act of publishing it — every subsequent build would reject every lab.

So the hash covers the manifest's **canonical-state identity**: ``schema_version`` plus
the full ``registry`` array. That is precisely the input a lab consumed. It changes when
records are added, superseded, or tombstoned (the lab genuinely is stale) and does not
change when the pipeline re-stamps a timestamp or re-hashes its own output.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

#: Repo root — ``src/agentic_dynamics/reporting/canonical_corpus.py`` -> four parents up.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent

#: The compacted canonical-state registry (written by ``scripts/generate_manifest.py``).
DATA_MANIFEST_PATH = PROJECT_ROOT / "experiments" / "data_manifest.json"

RESULTS_DIR = PROJECT_ROOT / "experiments" / "results"
STORIES_DIR = RESULTS_DIR / "stories"
REVIEWS_DIR = RESULTS_DIR / "reviews"
ANALYSIS_DIR = RESULTS_DIR / "analysis"

#: Conditions that were no-ops in the pre-fix corpus (``docs/data_integrity_findings.md``
#: treatment rule 1). Mirrors ``knowledge.story_ingestion.NOOP_CONDITIONS`` and
#: ``scripts/build_data.py``'s copy — duplicated rather than imported so this module stays
#: dependency-light (importing the knowledge plane drags in the chroma/neo4j stack, which a
#: lab book must never need).
NOOP_CONDITIONS = frozenset({"early_degrade", "bad_seed"})

#: The table names a lab may request. Each maps to one resolver below.
TABLES = ("story", "review", "analysis", "finding")

#: table name -> the :class:`CanonicalTables` attribute holding its rows. Declared once so
#: callers never re-derive it (and so adding a table is a single-place change).
TABLE_ATTRIBUTES = {
    "story": "stories",
    "review": "reviews",
    "analysis": "analysis",
    "finding": "findings",
}


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ManifestIdentity:
    """Who the input dataset *is* — the lineage a lab embeds and build_data re-checks.

    ``input_manifest_sha256`` is the projection hash described in the module docstring;
    ``registry_version`` is a human-readable version string combining the manifest schema
    version with the canonical row count, so a mismatch is legible in a log line without
    diffing hashes.
    """

    input_manifest_sha256: str
    registry_version: str
    n_rows: int
    n_current: int

    @classmethod
    def empty(cls) -> ManifestIdentity:
        """Identity of "no manifest" — an explicit absence, distinguishable from a real one.

        Deliberately NOT a plausible-looking hash: a lab built without a manifest must be
        rejected at publication, and an obviously-empty identity makes that unambiguous.
        """
        return cls(input_manifest_sha256="", registry_version="absent", n_rows=0, n_current=0)


def _canonical_json(obj: Any) -> bytes:
    """Stable JSON encoding for hashing: sorted keys, no incidental whitespace."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")


def read_manifest(manifest_path: Path | None = None) -> dict:
    """Load ``data_manifest.json``, degrading to ``{}`` when absent/unreadable.

    Mirrors ``scripts/registry.load_registry``'s file-fallback posture: a missing manifest
    is a *state*, not a crash. The caller (a lab) then emits an empty identity, and the
    publication gate rejects the output — the failure surfaces where it matters.
    """
    path = manifest_path or DATA_MANIFEST_PATH
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def manifest_identity(
    manifest: dict | None = None, *, manifest_path: Path | None = None
) -> ManifestIdentity:
    """Compute the canonical-state identity of a manifest.

    Pass either an already-loaded ``manifest`` dict or a path. The hash covers
    ``schema_version`` + the whole ``registry`` array (see the module docstring for why not
    the raw file bytes).
    """
    man = manifest if manifest is not None else read_manifest(manifest_path)
    rows = man.get("registry") or []
    if not man or not rows:
        return ManifestIdentity.empty()

    schema_version = str(man.get("schema_version", "unknown"))
    digest = hashlib.sha256(
        _canonical_json({"schema_version": schema_version, "registry": rows})
    ).hexdigest()
    n_current = sum(1 for r in rows if r.get("lifecycle_state") == "current")
    return ManifestIdentity(
        input_manifest_sha256=digest,
        registry_version=f"data-manifest/{schema_version}+{len(rows)}rows",
        n_rows=len(rows),
        n_current=n_current,
    )


def current_manifest_identity(manifest_path: Path | None = None) -> ManifestIdentity:
    """Identity of the manifest on disk right now — build_data's side of the comparison."""
    return manifest_identity(manifest_path=manifest_path)


# ---------------------------------------------------------------------------
# Row selection + payload joins
# ---------------------------------------------------------------------------


def registry_rows(manifest: dict) -> list[dict]:
    """The manifest's ``registry`` array (``[]`` when absent)."""
    return list(manifest.get("registry") or [])


def current_rows(manifest: dict, source_type: str) -> list[dict]:
    """Every ``lifecycle_state == "current"`` row of one ``source_type``.

    This single filter is what makes a lab's input canonical: tombstoned and superseded
    records never reach a measurement.
    """
    return [
        r
        for r in registry_rows(manifest)
        if r.get("source_type") == source_type and r.get("lifecycle_state") == "current"
    ]


def effective_story_condition(payload: dict) -> str:
    """A story's condition with the no-op relabel applied.

    ``docs/data_integrity_findings.md`` treatment rule 1: a story labelled
    ``early_degrade``/``bad_seed`` that carries no instrumented verdict
    (``test_executed_success`` is not a bool — the pre-fix cells never ran the independent
    test runner) received no actual perturbation, so its condition is corrected to
    ``clean``. Its cost and quality measurements stay valid; only the label was wrong.
    """
    condition = str(payload.get("perturbation_condition") or "")
    if condition in NOOP_CONDITIONS and not isinstance(payload.get("test_executed_success"), bool):
        return "clean"
    return condition


def _read_json(path: Path) -> dict | None:
    """Read one payload, returning ``None`` (never a fabricated stub) on any failure."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _story_path(story_id: str) -> Path | None:
    """Locate a story payload from its id.

    Story result filenames end in ``_<story_id>.json`` (``story.save_story_result``), and a
    ``story`` registry row's ``logical_locator`` *is* that id. The lookup is scoped to
    ``STORIES_DIR``'s top level, so remediation subdirectories
    (``stories/_remediation_contaminated/``) can never be picked up.
    """
    if not story_id:
        return None
    matches = sorted(p for p in STORIES_DIR.glob(f"*_{story_id}.json") if p.is_file())
    return matches[0] if matches else None


def resolve_stories(manifest: dict) -> list[dict]:
    """Every current ``story`` payload, condition-corrected and provenance-stamped.

    Each payload gains two underscore-prefixed keys so downstream labs never have to
    re-derive provenance:

    * ``_canonical_condition`` — the relabelled condition (use this, not the raw field)
    * ``_registry`` — ``{entity_id, knowledge_id, source_uri, lifecycle_state}``
    * ``_source_path`` — the resolved payload path, for a lab that needs the typed
      ``runtime.story.load_story_result`` loader rather than the raw dict. It is a
      *resolved* path (the registry chose it), so using it is still canonical.
    """
    out: list[dict] = []
    for row in current_rows(manifest, "story"):
        story_id = str(row.get("logical_locator") or "")
        path = _story_path(story_id)
        if path is None:
            continue
        payload = _read_json(path)
        if payload is None:
            continue
        payload["_canonical_condition"] = effective_story_condition(payload)
        payload["_source_path"] = str(path)
        payload["_registry"] = {
            "entity_id": row.get("entity_id"),
            "knowledge_id": row.get("knowledge_id"),
            "source_uri": row.get("source_uri"),
            "lifecycle_state": row.get("lifecycle_state"),
        }
        payload.setdefault("story_id", story_id)
        out.append(payload)
    return out


def resolve_reviews(manifest: dict) -> list[dict]:
    """Every current ``review`` payload.

    A ``review`` row's ``logical_locator`` is the story id, and the reviewer writes
    ``reviews/review_<story_id>.json`` (``scripts/finalize_reviews.py``). The payload gains
    ``_story_id`` so a lab can join reviews to stories without re-parsing file names.
    """
    out: list[dict] = []
    for row in current_rows(manifest, "review"):
        story_id = str(row.get("logical_locator") or "")
        path = REVIEWS_DIR / f"review_{story_id}.json"
        if not path.exists():
            continue
        payload = _read_json(path)
        if payload is None:
            continue
        payload["_story_id"] = story_id
        out.append(payload)
    return out


def resolve_analysis(manifest: dict) -> list[dict]:
    """Post-hoc analysis payloads for the current stories only.

    Analysis artifacts (``analysis/analysis_<story_id>.json``, written by
    ``scripts/analysis_worker.py``) are *derived* from a story and are not registered as
    their own ``source_type``. They are still canonical inputs here because the **story
    registry decides which ones exist**: an analysis whose story is tombstoned or
    unregistered is never read. That is the difference between a registry-filtered join
    and the ``glob("*.json")`` this module replaces.
    """
    out: list[dict] = []
    for row in current_rows(manifest, "story"):
        story_id = str(row.get("logical_locator") or "")
        path = ANALYSIS_DIR / f"analysis_{story_id}.json"
        if not story_id or not path.exists():
            continue
        payload = _read_json(path)
        if payload is None:
            continue
        payload["_story_id"] = story_id
        out.append(payload)
    return out


def _resolve_file_uri(source_uri: str) -> Path | None:
    """Resolve a ``file://`` registry ``source_uri`` to a repo-relative path.

    ``finding`` rows carry ``file://experiments/results/…`` URIs (the
    ``knowledge_ingestion.SOURCE_URI`` contract). Any other scheme (``story:``,
    ``review:``) belongs to a different resolver, so this returns ``None``.
    """
    if not source_uri or not source_uri.startswith("file://"):
        return None
    return PROJECT_ROOT / source_uri[len("file://") :]


def resolve_findings(manifest: dict) -> list[dict]:
    """Every current ``finding`` run — the single-task perturbation cells.

    A ``finding`` row points at an aggregate results file via ``source_uri`` and names the
    one cell inside it via ``logical_locator`` (== ``basename(run["workdir"])``). This is
    the corpus that carries ``perturbation_strength`` and ``operator``, which is what makes
    the formal Grit metric computable at all.

    Each returned run gains ``_registry`` provenance and ``_experiment`` (the parent file's
    experiment name). Structurally parallel to ``build_data._resolve_finding_entry``, minus
    that function's mapping into the retired summary's *field vocabulary* — labs want the
    measured fields under their real names.
    """
    out: list[dict] = []
    for row in current_rows(manifest, "finding"):
        path = _resolve_file_uri(str(row.get("source_uri") or ""))
        locator = str(row.get("logical_locator") or "")
        if path is None or not path.exists() or not locator:
            continue
        payload = _read_json(path)
        if payload is None:
            continue
        for run in payload.get("runs") or []:
            workdir = str(run.get("workdir") or "")
            if workdir.rsplit("/", 1)[-1] != locator:
                continue
            run = dict(run)  # never mutate the shared payload
            run["_experiment"] = payload.get("experiment", "")
            run["_registry"] = {
                "entity_id": row.get("entity_id"),
                "knowledge_id": row.get("knowledge_id"),
                "source_uri": row.get("source_uri"),
                "lifecycle_state": row.get("lifecycle_state"),
            }
            out.append(run)
            break
    return out


_RESOLVERS = {
    "story": resolve_stories,
    "review": resolve_reviews,
    "analysis": resolve_analysis,
    "finding": resolve_findings,
}


# ---------------------------------------------------------------------------
# The lab-facing entry point
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CanonicalTables:
    """The resolved canonical input a lab computes over, plus its identity.

    ``tables`` records which tables were requested; it becomes part of the
    ``input_dataset_id`` so two labs reading different slices are distinguishable.
    """

    identity: ManifestIdentity
    tables: tuple[str, ...] = ()
    stories: list[dict] = field(default_factory=list)
    reviews: list[dict] = field(default_factory=list)
    analysis: list[dict] = field(default_factory=list)
    findings: list[dict] = field(default_factory=list)

    @property
    def input_dataset_id(self) -> str:
        """Stable id of the input slice, e.g. ``canonical_registry/story+review``."""
        return (
            f"canonical_registry/{'+'.join(self.tables)}" if self.tables else "canonical_registry"
        )

    @property
    def is_empty(self) -> bool:
        """True when nothing resolved — the caller should say so rather than publish zeros."""
        return not (self.stories or self.reviews or self.analysis or self.findings)

    def stories_by_id(self) -> dict[str, dict]:
        """``story_id -> payload`` for join-style labs."""
        return {str(s.get("story_id") or ""): s for s in self.stories if s.get("story_id")}

    def rows(self, table: str) -> list[dict]:
        """Rows of one table by its *table name* (``"story"``, ``"finding"``, …).

        Saves every caller from re-deriving the name→attribute mapping
        (``"story" -> .stories``, ``"analysis" -> .analysis``), which is the kind of
        duplicated lookup that silently rots when a table is added.
        """
        attr = TABLE_ATTRIBUTES.get(table)
        if attr is None:
            raise ValueError(f"unknown canonical table {table!r}; known: {list(TABLE_ATTRIBUTES)}")
        return getattr(self, attr)


def load_canonical_tables(
    *tables: str,
    manifest_path: Path | None = None,
) -> CanonicalTables:
    """Resolve the requested canonical tables. **The only input door a lab may use.**

    ::

        tables = load_canonical_tables("story")            # story labs
        tables = load_canonical_tables("story", "review")  # join labs

    Unknown table names raise immediately — a typo must not silently yield an empty table
    that then publishes as "no effect measured".
    """
    requested = tuple(tables) or ("story",)
    unknown = [t for t in requested if t not in _RESOLVERS]
    if unknown:
        raise ValueError(f"unknown canonical table(s) {unknown}; known: {list(_RESOLVERS)}")

    manifest = read_manifest(manifest_path)
    identity = manifest_identity(manifest)
    resolved = {name: _RESOLVERS[name](manifest) for name in requested}

    return CanonicalTables(
        identity=identity,
        tables=requested,
        stories=resolved.get("story", []),
        reviews=resolved.get("review", []),
        analysis=resolved.get("analysis", []),
        findings=resolved.get("finding", []),
    )
