"""Rule 4 ``energy`` / EPM — the energy horizon surface (d5 Phase 3: a labeled scenario area).

Energy economics are MODELED/EXTERNAL, not live readings: EPM(t) is an external energy-price
scenario (IEA), the per-token energy model is an external benchmark, and the per-model energy
ranking is a design-table computation published in the website data. This projection serves
those sources with their provenance labels, and it renders the ONE thing that would be measured —
energy cost per session — as an explicit unknown, because the canonical corpus records no
energy field (rule 4's missing record field). No scenario number is ever presented as a reading.

The per-token constants are imported from ``measurement.efficiency`` (the single writer of the
energy model), not copied; the EPM scenarios and the ranking come from the published website
data (``apps/website/data.js``, generated by ``build_data.py``), injected by the caller.
"""

from __future__ import annotations

from typing import Any

from agentic_dynamics.measurement.efficiency import (
    ENERGY_PER_OUTPUT_TOKEN,
    ENERGY_PER_PROMPT_TOKEN,
    ENERGY_PER_REASONING_TOKEN,
)

SCHEMA = "energy-epm/v1"


def _unknown(reason: str, *, cls: str = "") -> dict[str, Any]:
    out: dict[str, Any] = {"state": "unknown", "reason": reason}
    if cls:
        out["class"] = cls
    return out


def build_energy(
    published: dict[str, Any] | None,
    *,
    now: str | None = None,
    source: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the energy/EPM payload. Pure given its inputs (``published`` injected)."""
    external = (published or {}).get("external_sources") or {}

    def _external(key: str) -> dict[str, Any] | None:
        entry = external.get(key)
        return dict(entry) if isinstance(entry, dict) else None

    baseline = _external("epm_baseline")
    aggressive = _external("epm_aggressive")
    epm: dict[str, Any] = (
        {
            "state": "published",
            "class": "[X]",
            "source": "apps/website/data.js external_sources (build_data.py)",
            "baseline": baseline,
            "aggressive": aggressive,
        }
        if (baseline or aggressive)
        else _unknown("published website data unavailable (apps/website/data.js)", cls="[X]")
    )

    ranking = (published or {}).get("energy_ranking")
    ranking_block: dict[str, Any] = (
        {
            "state": "published",
            "class": "[C]/[X]",
            "source": "apps/website/data.js energy_ranking (build_data.py design table)",
            "models": ranking,
        }
        if isinstance(ranking, list)
        else _unknown("published website data unavailable (apps/website/data.js)", cls="[C]/[X]")
    )

    return {
        "schema": SCHEMA,
        "generated_at": now,
        "source": dict(source or {}),
        "energy_model": {
            "per_prompt_token_j": ENERGY_PER_PROMPT_TOKEN,
            "per_output_token_j": ENERGY_PER_OUTPUT_TOKEN,
            "per_reasoning_token_j": ENERGY_PER_REASONING_TOKEN,
            "class": "[C]/[X]",
            "source": "measurement/efficiency.py ENERGY_PER_* (TokenPowerBench, Niu et al., AAAI 2026)",
        },
        "epm": epm,
        "energy_ranking": ranking_block,
        "measured_session_energy": _unknown(
            "no measured per-session energy on the canonical corpus (rule 4 missing record field)",
            cls="[M]",
        ),
        "flip_horizon": _unknown(
            "no owner for the EPM(t) horizon computation (rule 4 missing record field)",
            cls="[P]",
        ),
        "degraded": [],
    }
