#!/usr/bin/env python3
"""L0 game-board generator — the system's live snapshot (design: system_knowledge_abstraction).

Writes ``agent_config/system_snapshot.md`` (the shared mental model EVERY actor reads —
workers for orientation, the controller instead of triage, the supervisor as its assessment
baseline) from live state ONLY: git, Redis, the filesystem, the generated indices. The file
is derived — a hand-edit is overwritten by design. Every subsystem is best-effort: Redis
down, queue empty, a daemon absent — the section degrades gracefully, never blocks, never
fails. The snapshot is then rendered into the agent surfaces by ``_gen_instructions.py``
(INSTRUCTIONS includes ``system_snapshot.md``) and served read-only by the Control Room.

Usage: python3 scripts/system_snapshot.py [--out agent_config/system_snapshot.md]
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _sh(cmd: list[str], cwd: Path | None = None, timeout: int = 20) -> str:
    try:
        r = subprocess.run(
            cmd, cwd=cwd or REPO_ROOT, capture_output=True, text=True, timeout=timeout
        )
        return r.stdout.strip() if r.returncode == 0 else ""
    except Exception:  # noqa: BLE001 — best-effort: any subsystem may be unavailable
        return ""


def _redis() -> tuple[object | None, str]:
    """Best-effort Redis handle; returns (client, error) — (None, reason) on any failure."""
    try:
        import redis  # noqa: PLC0415 — import locally so a missing client never breaks the snapshot

        r = redis.Redis(host="127.0.0.1", port=6380, db=1, decode_responses=True, socket_timeout=3)
        r.ping()
        return r, ""
    except Exception as e:  # noqa: BLE001
        return None, f"unavailable ({type(e).__name__})"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=str(REPO_ROOT / "agent_config" / "system_snapshot.md"),
        help="output path (default: agent_config/system_snapshot.md)",
    )
    args = parser.parse_args()

    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    lines: list[str] = []
    add = lines.append
    add("<!-- GENERATED by scripts/system_snapshot.py — a hand-edit is overwritten. -->")
    add("# System snapshot — the game board (L0)")
    add("")
    add(f"_generated_at: {now}_  ·  _source: live state only (git / Redis / filesystem / indices)_")
    add("")

    # ── main + chronological history ──────────────────────────────────────────
    add("## main")
    head = _sh(["git", "rev-parse", "--short", "HEAD"])
    subject = _sh(["git", "log", "-1", "--format=%s"])
    add(f"- HEAD: `{head}` — {subject}")
    branch = _sh(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    add(f"- branch: `{branch}`")
    add("")
    add("### recent chronological history (last 12 commits)")
    add("")
    add("```")
    add(_sh(["git", "log", "--format=%h %ad %s", "--date=format:%m-%d %H:%M", "-12"]) or "(no history)")
    add("```")
    add("")

    # ── the spec index (the lifecycle board) ──────────────────────────────────
    add("## spec lifecycle (experiments/specs/index.json)")
    index_path = REPO_ROOT / "experiments" / "specs" / "index.json"
    try:
        idx = json.loads(index_path.read_text(encoding="utf-8"))
        specs = idx.get("specs") or []
        from collections import Counter  # noqa: PLC0415

        statuses = Counter(s.get("status", "?") for s in specs)
        add(
            f"- total: {len(specs)}  ("
            + ", ".join(f"{k} {v}" for k, v in sorted(statuses.items()))
            + ")"
        )
        recent = sorted(
            (s for s in specs if s.get("last_run_at")), key=lambda s: s["last_run_at"], reverse=True
        )[:4]
        for s in recent:
            add(f"- {s.get('name')} ({s.get('status')}) — {s.get('last_run_at')}")
    except Exception:  # noqa: BLE001
        add("- index unreadable")
    add("")

    # ── registry + corpus ─────────────────────────────────────────────────────
    add("## registry + corpus")
    registry_index = REPO_ROOT / "experiments" / "results" / "registry_index.jsonl"
    if registry_index.exists():
        add(f"- registry entities: {sum(1 for _ in registry_index.open(encoding='utf-8'))}")
    else:
        add("- registry index absent")
    stories = list((REPO_ROOT / "experiments" / "results" / "stories").glob("*.json"))
    if stories:
        spend = 0.0
        ok = 0
        for f in stories:
            try:
                d = json.loads(f.read_text(encoding="utf-8"))
                s = d.get("summary") or {}
                spend += s.get("total_cost") or 0
                if s.get("all_successful"):
                    ok += 1
            except Exception:  # noqa: BLE001
                pass
        add(f"- stories: {len(stories)} ({ok} successful) · measured spend ${spend:.2f}")
    add("")

    # ── the running machine ───────────────────────────────────────────────────
    add("## running machine")
    r, r_err = _redis()
    if r is None:
        add(f"- redis (6380/db1): {r_err}")
    else:
        add(f"- redis (6380/db1): alive — story_jobs {r.llen('story_jobs')} · story_status {r.hlen('story_status')}")
        pipeline = sorted(k for k in r.keys("pipeline:*:current") if k.startswith("pipeline:"))
        for k in pipeline:
            add(f"- {k}: phase `{r.get(k)}`")
    workers = _sh(["ps", "-eo", "comm"])
    for proc in ("worker.py", "pipeline.py", "run_workflow.py", "analyze_stories.py"):
        n = sum(1 for p in workers.splitlines() if p and proc in p)
        if n:
            add(f"- {proc}: {n} running")
    # Chroma (the KB's dense store — a Docker container publishing 8000; the Control
    # Room's DEFAULT port collides with it, which is why the portal lives on 8001 —
    # the run script's FINOPS_PORT=8001). Best-effort: the container + collection counts.
    chroma_rows = _sh(["docker", "ps", "--filter", "name=chromadb", "--format", "{{.Names}} up {{.Status}}"])
    if chroma_rows:
        add(f"- chromadb (docker): {chroma_rows}")
        try:
            import chromadb  # noqa: PLC0415 — optional; a missing client degrades the row

            cc = chromadb.HttpClient(host="127.0.0.1", port=8000)
            counts = [
                f"{getattr(x, 'name', '?')}={x.count()}"
                for x in cc.list_collections()
                if getattr(x, "name", "") in ("session_embeddings", "knowledge_chunks_v1")
            ]
            if counts:
                add(f"- chroma collections: {', '.join(counts)}")
        except Exception:  # noqa: BLE001 — a down store degrades gracefully
            add("- chroma collections: unavailable")
    add("")

    # ── campaigns in flight (worktrees with live sessions) ───────────────────
    add("## campaigns in flight (worktrees)")
    wl = _sh(["git", "worktree", "list", "--porcelain"])
    wdirs = [
        Path(line.split(" ", 1)[1])
        for line in wl.splitlines()
        if line.startswith("worktree ") and "/tmp/" in line
    ]
    if not wdirs:
        add("- none (all campaigns idle)")
    for wd in wdirs:
        sess = wd / ".instrument" / "session.jsonl"
        if sess.exists():
            mtime = datetime.datetime.fromtimestamp(
                sess.stat().st_mtime, tz=datetime.timezone.utc
            )
            age_min = int((datetime.datetime.now(datetime.timezone.utc) - mtime).total_seconds() // 60)
            add(f"- `{wd.name}` — session last step {age_min} min ago")
    add("")

    # ── awaiting the controller's permanence decision ────────────────────────
    add("## awaiting permanence (the controller's gate)")
    add("")
    add("_Worktree branches are proposals; the controller decides what merges into the")
    add("chronological history (main). Nothing merges without the controller's sign-off._")
    if wdirs:
        for wd in wdirs:
            b = _sh(["git", "-C", str(wd), "rev-parse", "--abbrev-ref", "HEAD"])
            n = _sh(["git", "-C", str(wd), "rev-list", "--count", "main..HEAD"])
            add(f"- `{wd.name}` on `{b}` — {n} commits ahead of main, awaiting the decision")
    else:
        add("- none")
    add("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
