import type { Page, PageData } from './types';

const STYLES = `
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  color: #1f2933;
  background: #ffffff;
  line-height: 1.6;
}
.container { max-width: 760px; margin: 0 auto; padding: 2rem 1.5rem 4rem; }
a { color: #2563eb; text-decoration: none; }
a:hover { text-decoration: underline; }
.site-header { border-bottom: 1px solid #e4e7eb; margin-bottom: 1.5rem; padding-bottom: 1rem; }
h1.title { margin: 0.25rem 0 0.5rem; }
.back { font-size: 0.9rem; }
.meta { color: #52606d; font-size: 0.9rem; }
.date { margin-right: 0.5rem; }
.tag {
  display: inline-block;
  background: #eff6ff;
  color: #1e40af;
  border: 1px solid #bfdbfe;
  border-radius: 999px;
  padding: 0.1rem 0.6rem;
  font-size: 0.8rem;
  margin-right: 0.4rem;
}
main { margin-top: 1.5rem; }
main img { max-width: 100%; }
.page-list { list-style: none; margin: 0; padding: 0; }
.page-list .entry { padding: 0.75rem 0; border-bottom: 1px solid #e4e7eb; }
.page-list .entry:last-child { border-bottom: none; }
.entry-title { margin: 0 0 0.25rem; font-size: 1.25rem; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e4e7eb; color: #52606d; font-size: 0.85rem; }
`;

export function escapeHtml(value: unknown): string {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function pageTitle(data: PageData, fallback: string): string {
  const title = data && data.title && String(data.title).trim();
  return title ? title : fallback;
}

function renderMeta(page: Pick<Page, 'data'>): string {
  const parts: string[] = [];
  if (page.data.date) {
    parts.push(`<span class="date">${escapeHtml(page.data.date)}</span>`);
  }
  const tags = Array.isArray(page.data.tags) ? page.data.tags.map(String) : [];
  if (tags.length > 0) {
    const rendered = tags.map((t) => `<span class="tag">${escapeHtml(t)}</span>`).join('');
    parts.push(`<span class="tags">${rendered}</span>`);
  }
  return parts.join(' ');
}

export function buildPageHtml(page: Page): string {
  const title = pageTitle(page.data, page.slug);
  const meta = renderMeta(page);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>${STYLES}</style>
</head>
<body>
  <div class="container">
    <header class="site-header">
      <a class="back" href="./index.html">&larr; All pages</a>
      <h1 class="title">${escapeHtml(title)}</h1>
      ${meta ? `<p class="meta">${meta}</p>` : ''}
    </header>
    <main>
${page.html}
    </main>
    <footer>Generated by ssg</footer>
  </div>
</body>
</html>
`;
}

export function buildIndexHtml(pages: Page[]): string {
  const entries = pages
    .map((page) => {
      const title = pageTitle(page.data, page.slug);
      const meta = renderMeta(page);
      return `    <li class="entry">
      <a href="./${escapeHtml(page.outputFile)}"><h2 class="entry-title">${escapeHtml(title)}</h2></a>
      ${meta ? `<p class="meta">${meta}</p>` : ''}
    </li>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>All pages</title>
  <style>${STYLES}</style>
</head>
<body>
  <div class="container">
    <header class="site-header">
      <h1 class="title">All pages</h1>
    </header>
    <ul class="page-list">
${entries}
    </ul>
    <footer>Generated by ssg</footer>
  </div>
</body>
</html>
`;
}
