import fs from 'fs';
import path from 'path';
import Handlebars from 'handlebars';
import { Page } from './types';

export const DEFAULT_TEMPLATES_DIR = 'templates';
export const DEFAULT_TEMPLATE = 'default';
export const DEFAULT_LAYOUT = 'default';
export const NO_LAYOUT = 'none';

const TEMPLATE_EXTS = ['.hbs', '.ejs'];

function escapeHtml(input: unknown): string {
  return String(input)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const BUILTIN_LAYOUT = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{title}}</title>
</head>
<body>
{{> nav}}
<main>
{{{body}}}
</main>
</body>
</html>
`;

const BUILTIN_PAGE_TEMPLATE = `<article>
<h1>{{title}}</h1>
{{#if date}}<time datetime="{{date}}">{{date}}</time>{{/if}}
<div class="tags">{{#each tags}}<a class="tag" href="?tag={{this}}">{{this}}</a>{{/each}}</div>
<div class="content">
{{{html}}}
</div>
</article>
`;

const BUILTIN_INDEX_TEMPLATE = `<main>
<h1>Pages</h1>
<ul class="pages">
{{#each pages}}
    <li class="page">
      <h2><a href="{{slug}}.html">{{title}}</a></h2>
      <p class="meta">{{#if date}}<time datetime="{{date}}">{{date}}</time> {{/if}}{{#each tags}}<span class="tag">{{this}}</span> {{/each}}</p>
      <p class="excerpt">{{excerpt}}</p>
    </li>
{{/each}}
</ul>
</main>
`;

const BUILTIN_PARTIALS: Record<string, string> = {
  header: '<header><a class="site-brand" href="./index.html">Home</a></header>',
  nav: '<nav><a href="./index.html">Home</a></nav>',
  footer: '<footer><p>Generated by SSG</p></footer>',
};

type TemplateRenderer = (context: Record<string, unknown>) => string;

interface TemplateSource {
  name: string;
  source: string;
  ext: string;
  render?: TemplateRenderer;
}

function compileEjs(
  source: string,
  include: (name: string, context: Record<string, unknown>) => string
): TemplateRenderer {
  const js: string[] = [];
  const re = /<%(=|-|#)([\s\S]*?)%>|<%([\s\S]*?)%>/g;
  let last = 0;
  let match: RegExpExecArray | null;
  while ((match = re.exec(source)) !== null) {
    const text = source.slice(last, match.index);
    if (text) js.push(`__out.push(${JSON.stringify(text)});`);
    const marker = match[1] === undefined ? '' : match[1];
    const code = match[2] === undefined ? match[3] : match[2];
    if (marker === '=') {
      js.push(`__out.push(__escape(${code.trim()}));`);
    } else if (marker === '-') {
      const trimmed = code.trim();
      const includeMatch = /^include\s*\(([\s\S]*)\)$/.exec(trimmed);
      if (includeMatch) {
        js.push(`__out.push(__include(${includeMatch[1]}));`);
      } else {
        js.push(`__out.push(${trimmed});`);
      }
    } else if (marker === '#') {
      // comment: skip
    } else {
      js.push(code);
    }
    last = re.lastIndex;
  }
  const tail = source.slice(last);
  if (tail) js.push(`__out.push(${JSON.stringify(tail)});`);

  const body = [
    'var __out = [];',
    'with (locals) {',
    ...js,
    '}',
    'return __out.join("");',
  ].join('\n');

  // eslint-disable-next-line no-new-func
  const fn = new Function('locals', '__escape', '__include', body);

  return (context: Record<string, unknown>) => {
    const locals = { ...context };
    return fn(
      locals,
      escapeHtml,
      (name: string, extra?: Record<string, unknown>) =>
        include(name, { ...locals, ...extra })
    );
  };
}

export class TemplateEngine {
  private templates = new Map<string, TemplateSource>();
  private layouts = new Map<string, TemplateSource>();
  private partials = new Map<string, TemplateSource>();
  private hbs = Handlebars.create();

  constructor(templatesDir?: string) {
    this.registerBuiltins();
    if (templatesDir && fs.existsSync(templatesDir)) {
      this.loadFromDir(templatesDir);
    }
    this.registerPartials();
  }

  private registerBuiltins(): void {
    this.templates.set(DEFAULT_TEMPLATE, {
      name: DEFAULT_TEMPLATE,
      source: BUILTIN_PAGE_TEMPLATE,
      ext: 'hbs',
    });
    this.templates.set('index', {
      name: 'index',
      source: BUILTIN_INDEX_TEMPLATE,
      ext: 'hbs',
    });
    this.layouts.set(DEFAULT_LAYOUT, {
      name: DEFAULT_LAYOUT,
      source: BUILTIN_LAYOUT,
      ext: 'hbs',
    });
    for (const name of Object.keys(BUILTIN_PARTIALS)) {
      this.partials.set(name, {
        name,
        source: BUILTIN_PARTIALS[name],
        ext: 'hbs',
      });
    }
  }

  private loadFromDir(templatesDir: string): void {
    this.loadSources(path.join(templatesDir, 'layouts'), this.layouts);
    this.loadSources(path.join(templatesDir, 'partials'), this.partials);
    this.loadSources(templatesDir, this.templates);
  }

  private loadSources(dir: string, target: Map<string, TemplateSource>): void {
    if (!fs.existsSync(dir)) return;
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      const fullExt = path.extname(entry.name).toLowerCase();
      if (!TEMPLATE_EXTS.includes(fullExt)) continue;
      const name = path.basename(entry.name, fullExt);
      const source = fs.readFileSync(path.join(dir, entry.name), 'utf8');
      target.set(name, {
        name,
        source,
        ext: fullExt.slice(1),
      });
    }
  }

  private registerPartials(): void {
    for (const [name, src] of this.partials) {
      if (src.ext === 'hbs') {
        this.hbs.registerPartial(name, src.source);
      }
    }
  }

  private makeRenderer(src: TemplateSource): TemplateRenderer {
    if (src.ext === 'ejs') {
      return compileEjs(src.source, (name, context) =>
        this.renderPartial(name, context)
      );
    }
    const compiled = this.hbs.compile(src.source);
    return (context) => compiled(context);
  }

  private renderSource(src: TemplateSource, context: Record<string, unknown>): string {
    if (!src.render) {
      src.render = this.makeRenderer(src);
    }
    return src.render(context);
  }

  hasTemplate(name: string): boolean {
    return this.templates.has(name);
  }

  hasLayout(name: string): boolean {
    return this.layouts.has(name);
  }

  renderTemplate(name: string, context: Record<string, unknown>): string {
    const src = this.templates.get(name);
    if (!src) throw new Error(`template not found: ${name}`);
    return this.renderSource(src, context);
  }

  renderLayout(name: string, context: Record<string, unknown>): string {
    const src = this.layouts.get(name);
    if (!src) throw new Error(`layout not found: ${name}`);
    return this.renderSource(src, context);
  }

  renderPartial(name: string, context: Record<string, unknown>): string {
    const src = this.partials.get(name);
    if (!src) throw new Error(`partial not found: ${name}`);
    return this.renderSource(src, context);
  }
}

export function pageContext(page: Page): Record<string, unknown> {
  return {
    title: page.title,
    slug: page.slug,
    date: page.date,
    tags: page.tags,
    body: page.body,
    html: page.html,
    excerpt: page.excerpt,
    filePath: page.filePath,
    template: page.template,
    layout: page.layout,
  };
}

export function renderPage(
  page: Page,
  engine: TemplateEngine = new TemplateEngine(DEFAULT_TEMPLATES_DIR)
): string {
  const templateName = page.template || DEFAULT_TEMPLATE;
  const content = engine.renderTemplate(templateName, pageContext(page));
  if (page.layout === NO_LAYOUT) return content;
  const layoutName = page.layout || DEFAULT_LAYOUT;
  return engine.renderLayout(layoutName, { ...pageContext(page), body: content });
}

export function renderIndex(
  pages: Page[],
  engine: TemplateEngine = new TemplateEngine(DEFAULT_TEMPLATES_DIR)
): string {
  const context = { title: 'Home', pages };
  const content = engine.renderTemplate('index', context);
  return engine.renderLayout(DEFAULT_LAYOUT, { ...context, body: content });
}
