import type { Page } from './types';

export interface SiteConfig {
  title: string;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function pageTitle(page: Page): string {
  return page.data.title ?? page.slug;
}

function layout(title: string, body: string): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${escapeHtml(title)}</title>`,
    '</head>',
    '<body>',
    body,
    '</body>',
    '</html>',
  ].join('\n');
}

export function renderPage(page: Page, config: SiteConfig): string {
  const title = pageTitle(page);
  const meta = page.data.date ? `<p class="date">${escapeHtml(page.data.date)}</p>` : '';
  const tags = page.data.tags && page.data.tags.length > 0
    ? `<p class="tags">${page.data.tags.map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join(' ')}</p>`
    : '';
  const body = [
    '<header>',
    `<h1>${escapeHtml(title)}</h1>`,
    meta,
    tags,
    '</header>',
    '<main>',
    page.html,
    '</main>',
    `<footer>Generated by ${escapeHtml(config.title)}</footer>`,
  ].join('\n');
  return layout(title, body);
}

export function renderIndex(pages: Page[], config: SiteConfig): string {
  const sorted = [...pages].sort((a, b) => {
    const dateA = a.data.date ? Date.parse(a.data.date) : Number.NEGATIVE_INFINITY;
    const dateB = b.data.date ? Date.parse(b.data.date) : Number.NEGATIVE_INFINITY;
    if (dateA !== dateB) return dateB - dateA;
    return pageTitle(a).localeCompare(pageTitle(b));
  });

  const items = sorted.map((page) => {
    const date = page.data.date ? `<time datetime="${escapeHtml(page.data.date)}">${escapeHtml(page.data.date)}</time> ` : '';
    const tags = page.data.tags && page.data.tags.length > 0
      ? ` <em>(${page.data.tags.map((tag) => escapeHtml(tag)).join(', ')})</em>`
      : '';
    return `<li><a href="${escapeHtml(page.link)}">${escapeHtml(pageTitle(page))}</a> ${date}${tags}</li>`;
  }).join('\n');

  const body = [
    '<header>',
    `<h1>${escapeHtml(config.title)}</h1>`,
    '</header>',
    '<main>',
    sorted.length > 0 ? `<ul>\n${items}\n</ul>` : '<p>No pages found.</p>',
    '</main>',
  ].join('\n');

  return layout(config.title, body);
}
